(function () {
  'use strict';
  const D = X_DATA, E = X_ENGINE, KEY = 'XIAN-ZHI-DIAN-v1';
  const $ = s => document.querySelector(s);
  const esc = v => String(v == null ? '' : v).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const num = n => Number(n || 0).toLocaleString('zh-CN');
  const glyphs = {
    mountain:'m2 19 7-13 5 9 3-5 5 9H2m4-7 3 2 3-2',
    sword:'m14 3 7-1-1 7-11 11-5-5zM3 21l4-4m-4-3 7 7',
    book:'M3 4h6a3 3 0 0 1 3 3v14a4 4 0 0 0-4-2H3zm18 0h-6a3 3 0 0 0-3 3m9-3v15h-5a4 4 0 0 0-4 2',
    leaf:'M20 3C9 2 2 7 4 15s14 7 16-12zM4 20 16 8m-7 7v-5m3 2h5',
    flame:'M13 2c1 7-6 8-3 12 1-2 3-3 5-4 0 5 5 5 3 10-3 5-13 3-13-3 0-5 6-6 8-15z',
    sun:'M12 2v2m0 16v2M2 12h2m16 0h2M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2M17 12a5 5 0 1 1-10 0 5 5 0 0 1 10 0',
    moon:'M20 15A9 9 0 0 1 9 4a9 9 0 1 0 11 11z',
    gem:'m3 8 4-5h10l4 5-9 13L3 8zm0 0h18M8 8l4 13 4-13m-9-5 1 5 4-5 4 5 1-5',
    bag:'M8 3h8l-2 5 6 10a3 3 0 0 1-3 4H7a3 3 0 0 1-3-4l6-10-2-5zm2 5h4m-6 6h8',
    flask:'M9 2h6m-5 0v8l-6 9a2 2 0 0 0 2 3h12a2 2 0 0 0 2-3l-6-9V2M7 16h10',
    scroll:'M7 3h12v14H7a3 3 0 0 1-3-3V6a3 3 0 0 1 3-3zm0 0v11M7 17v3h14v-3M10 7h6m-6 4h6',
    shield:'m12 2 9 4v6c0 6-9 10-9 10S3 18 3 12V6zm-5 10 3 3 7-7',
    heart:'M20 5c-3-3-6 0-8 2-2-2-5-5-8-2s0 7 8 14c8-7 11-11 8-14z',
    compass:'M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0m-6-4-3 6-5 2 2-5z',
    temple:'m2 9 10-7 10 7M4 9h16M6 9v11m6-11v11m6-11v11M3 22h18',
    users:'M16 21v-3a4 4 0 0 0-4-4H7a4 4 0 0 0-4 4v3m17 0v-3a4 4 0 0 0-3-4M12 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0m4-3a3 3 0 0 1 0 6',
    paw:'M7 14c-1-5 4-8 6-5 2 2 1 3 4 5 5 6-1 8-5 6-6 2-10-1-5-6zM4 6v3m5-6v3m6-3v3m5 0v3',
    arrow:'M3 12h18m-6-6 6 6-6 6', plus:'M12 5v14M5 12h14', close:'m6 6 12 12M6 18 18 6',
    help:'M9 8a3 3 0 1 1 5 2c-2 1-2 2-2 3m0 4h.01M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',
    save:'M5 3h12l4 4v14H3V3zm2 0v6h10V3M7 21v-7h10v7',
    refresh:'M20 7a8 8 0 1 0 0 10m0-14v5h-5', star:'m12 2 3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1z',
    hammer:'m3 21 10-10m-3-5 5-4 7 7-4 5z', cloud:'M6 18a5 5 0 1 1 0-10 7 7 0 0 1 13 3 4 4 0 0 1 0 8H6'
  };
  const icon = name => /^[\u4e00-\u9fff◉]$/.test(name || '') ? `<span class="han-icon" aria-hidden="true">${esc(name)}</span>` : `<svg class="icon" aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="${glyphs[name] || glyphs.star}"/></svg>`;
  const landscape = `<svg class="landscape" viewBox="0 0 1000 160" preserveAspectRatio="xMidYMax slice" aria-hidden="true"><circle cx="770" cy="54" r="28" fill="currentColor" opacity=".11"/><path d="m280 160 160-123 78 68 101-82 130 107 92-49 159 79z" fill="currentColor" opacity=".05"/><path d="m110 160 115-65 60 31 115-86 97 98 73-45 77 67zm405 0 126-94 82 81 69-36 90 49z" fill="currentColor" opacity=".08"/><path d="m0 160 176-41 97 29 104-18 126 30zm653 0 137-33 103 20 107-16v29z" fill="currentColor" opacity=".10"/></svg>`;
  let state = null, filter = '修行', draft = null, toastTimer, shopTab = 'goods', receipt = null, loadError = '', saveOK = true;
  let worldView = '', worldReceipt = null, sectTab = 'admission', combatMode = 'spar', bidDrafts = {};
  try {
    const raw = localStorage.getItem(KEY);
    if (raw) { const saved = JSON.parse(raw); if (saved.format !== 'XIUXIAN-LIFE') throw Error('存档格式不符'); state = E.validate(saved.state); }
  } catch (_) { loadError = '原存档暂时无法读取。可从存档管理导入备份，或重新启程。'; }
  $('#modal-root').innerHTML = '<dialog id="game-dialog" aria-labelledby="dialog-title"></dialog><input id="import-file" type="file" accept="application/json,.json" hidden>';
  const dialog = $('#game-dialog');
  function toast(text) { clearTimeout(toastTimer); $('#toast').textContent = text; $('#toast').classList.add('visible'); toastTimer = setTimeout(() => $('#toast').classList.remove('visible'), 3500); }
  function save() { if (!state) return; try { localStorage.setItem(KEY, JSON.stringify({format:'XIUXIAN-LIFE',savedAt:new Date().toISOString(),state})); saveOK = true; } catch (_) { saveOK = false; toast('浏览器暂时无法保存，请从存档管理导出备份。'); } }
  function modal(html, wide = false) { dialog.className = wide ? 'wide-dialog' : ''; dialog.innerHTML = html; if (!dialog.open) dialog.showModal(); dialog.scrollTop = 0; $('#dialog-title')?.focus({preventScroll:true}); }
  function close() { dialog.close(); }
  function top(kicker) { return `<div class="dialog-top"><span class="eyebrow">${esc(kicker)}</span><button class="icon-button" data-command="close" aria-label="关闭弹窗">${icon('close')}</button></div>`; }
  function heading(title, sub = '') { return `<h2 id="dialog-title" tabindex="-1">${esc(title)}</h2>${sub ? `<p class="dialog-lead">${esc(sub)}</p>` : ''}`; }
  function chips(effects) { return `<div class="effect-chips">${Object.entries(effects || {}).filter(([,v]) => v !== 0).map(([k,v]) => `<span class="effect-chip ${v < 0 ? 'loss' : 'gain'}">${esc(E.effectsText({[k]:v}))}</span>`).join('')}</div>`; }
  function notes(lines, className = '') { return lines?.length ? `<ul class="notes ${className}">${lines.map(t => `<li>${esc(t)}</li>`).join('')}</ul>` : ''; }
  function progress(label, value, max, color = '') { const safe = Math.min(max, Math.max(0, value)); return `<div class="meter-label"><span>${esc(label)}</span><b>${num(value)} <small>/ ${num(max)}</small></b></div><div class="meter ${color}" role="meter" aria-label="${esc(label)}" aria-valuemin="0" aria-valuemax="${max}" aria-valuenow="${safe}"><i style="width:${Math.min(100, safe / max * 100)}%"></i></div>`; }
  const find = (list,id) => list.find(x => x.id === id);
  function lifespanTable(){return `<dl class="lifespan-table">${D.realms.map(r=>`<div><dt>${esc(r.name)}</dt><dd>${r.lifespan===null?'无尽':`${num(r.lifespan)} 岁`}</dd></div>`).join('')}</dl>`;}
  function lifespanPanel(){const life=E.lifespanStatus(state),remaining=life.remainingMonths,near=!life.immortal&&remaining<=120;return `<div class="lifespan-panel ${near?'near-limit':''}"><div class="lifespan-heading"><span>寿元上限 <b>${life.immortal?'无尽':`${num(life.limit)} 岁`}</b></span><strong>${life.immortal?'与天地同寿':`余 ${esc(life.remainingText||E.formatDuration(remaining))}`}</strong></div>${life.immortal?'':`<div class="meter ${near?'red':'gold'}" role="meter" aria-label="剩余寿元（月）" aria-valuemin="0" aria-valuemax="${life.limit*12}" aria-valuenow="${Math.max(0,remaining)}" aria-valuetext="${esc(life.remainingText||E.formatDuration(remaining))}"><i style="width:${Math.max(0,Math.min(100,remaining/(life.limit*12)*100))}%"></i></div>`}${near?`<p class="lifespan-warning" role="status">${remaining===0?'寿元已尽，此生长卷落定。':`寿元将尽，尚余 ${esc(E.formatDuration(remaining))}。行动须在寿限前完成，破境可延长寿限。`}</p>`:life.immortal?'<p>已超脱寿元桎梏，此生仙途圆满。</p>':'<p>修炼与游历会经过岁月；消耗的是余下时光，不会降低寿元上限。</p>'}</div>`;}
  function worldDuration(key,status){return status?.durationText||E.formatDuration(status?.months??D.worldTimes[key]??0);}
  function timeReceipt(r){return `<div class="receipt-time">${icon('moon')}<span>${r.months?`此行经过 ${esc(E.formatDuration(r.months))}`:'即刻完成，不消耗时间'} · ${esc(E.timeStatus(state).dateText)}</span></div>`;}
  function receiptNotes(r){return notes([...new Set([...(r.changes||[]),...(r.notes||[])])],'report-notes');}
  function birthPreview(){return E.create({name:draft.name,path:draft.path,talents:draft.talents,seed:draft.birthSeed});}
  function rootDetails(s){const root=E.rootStatus(s);return `<section class="root-birth-card"><div class="root-birth-heading"><span class="birth-root-seal">${esc(root.gradeName.slice(0,1))}</span><div><span class="eyebrow">此生天定 · ${esc(root.gradeName)}</span><h3>${esc(root.name)}</h3><p>${root.elementNames.map(esc).join(' · ')}</p></div></div><p>${esc(root.desc)}</p><div class="root-grade-effects"><span>正向修为收益 <b>×${root.cultivationMultiplier}</b></span><span>破境成功率 <b>${root.breakthroughBonus>=0?'+':''}${Math.round(root.breakthroughBonus*100)} 个百分点</b></span></div><p class="root-birth-note">灵根已在出生时确定。重抽天赋、选择流派均不会改变这一份资质。</p></section>`;}
  function sectRankCard(){const status=E.sectStatus(state);if(!status.sect)return '';const rank=status.rank,next=status.nextRank;return `<section class="sect-rank-card"><div class="section-top"><div><span class="eyebrow">${esc(status.sect.name)} · 宗门职务</span><h3>${esc(rank?.name||'初入山门')}</h3></div><b class="rank-merit">累计功勋 ${num(status.merit)}</b></div>${rank?`<p>${esc(rank.desc)}</p>${passiveDetails(rank)}`:''}${next?`<div class="promotion-target"><span>下一职务 · <b>${esc(next.name)}</b></span><span>境界 ${esc(D.realms[next.requireRealm].name)} · 累计功勋 ${num(next.requireMerit)}</span></div>${progress('晋升功勋',status.merit,Math.max(1,next.requireMerit),'gold')}<details class="rank-next-benefits"><summary>晋升后获得的能力</summary>${passiveDetails(next)}</details><button class="primary-button" data-command="promote" ${status.canPromote?'':'disabled'}>晋升${esc(next.name)} · ${esc(worldDuration('promotion'))}</button>${!status.canPromote?`<p class="world-card-reason">${esc(status.reason)}</p>`:''}`:'<p class="rank-complete">已担宗门最高职务。</p>'}<p class="rank-explanation">功勋记录当前宗门中累计获得的正向贡献，兑换物品不会扣减功勋。晋升不花贡献余额。</p></section>`;}
  function nextLifespanText(){const life=E.lifespanStatus(state);return life.nextLimit===null?'破境后寿元无尽 · 与天地同寿':`破境后寿元 ${num(life.nextLimit)} 岁 · 上限增加 ${num(life.gain)} 年`;}
  function worldPanel(){const status=E.worldStatus(state),moral=E.moralityStatus(state),partner=D.companions.map(c=>({meta:c,status:E.companionStatus(state,c.id)})).find(c=>c.status.isPartner);return `<section class="panel world-panel"><div class="section-top"><div><span class="eyebrow">${E.realmInfo(state).world==='immortal'?'仙界烟云':'人间山海'} · 修行之外</span><h2>天地游历</h2></div><span class="activity-count time-based">岁月随行 · 各有耗时</span></div><div class="world-entries">${[['facilities','temple','宗门','拜师晋升传承'],['companions','heart','道侣','相知共修'],['auction','gem','拍卖场','封价竞灵物'],['dungeons','compass','秘境','三关寻机缘'],['combat','sword','对战','切磋或争夺']].map(([id,symbol,name,desc])=>`<button data-world="${id}">${icon(symbol)}<b>${name}</b><span>${desc}</span></button>`).join('')}</div><div class="world-footer"><div class="morality-line ${moral.value>=20?'good':moral.value<=-20?'evil':''}"><span>善恶 <b>${moral.value>0?'+':''}${moral.value}</b> · ${esc(moral.title)}</span><p>${esc(moral.desc)}</p></div><p class="world-rule">${esc(status.reason||'交往、拍卖、秘境与对战都会经过月份，结果结算后年龄与剩余寿元同步变化。')}<span>普通买卖、宗门兑换、离开秘境即刻完成。</span></p></div>${partner?`<div class="partner-strip">${icon('heart')}<span>道侣 · <b>${esc(partner.meta.name)}</b>，羁绊 ${partner.status.affection} / 100</span><button class="link-button" data-jump="partner-cultivate">查看同心共修 ${icon('arrow')}</button></div>`:''}</section>`;}
  function worldReceiptHTML(){return worldReceipt?`<section class="receipt world-receipt" id="world-receipt" tabindex="-1" role="status"><b>${esc(worldReceipt.title)}</b><p>${esc(worldReceipt.text)}</p>${timeReceipt(worldReceipt)}${chips(worldReceipt.effects)}${receiptNotes(worldReceipt)}</section>`:'';}
  function worldHeading(kicker,title,description){const s=E.worldStatus(state);return `${top(kicker)}${heading(title,description)}<div class="world-statusbar"><span>${esc(E.timeStatus(state).dateText)} · ${esc(E.timeStatus(state).ageText)}</span><b>寿元余 ${esc(E.lifespanStatus(state).remainingText||'无尽')}</b></div>${s.reason?`<p class="world-blocker">${esc(s.reason)}</p>`:''}<p class="calendar-refresh">拍品、年度相处与交手限制随新年刷新：${esc(s.nextRefreshText||`第 ${state.year+1} 年 1 月`)}</p>${worldReceiptHTML()}`;}
  function openWorld(view){if(!state){toast('先开启一段仙途，再走进天地。');return;}worldView=view;worldReceipt=null;showWorld();}
  function showWorld(){({facilities:showSects,companions:showCompanions,auction:showAuction,dungeons:showDungeons,combat:showCombat})[worldView]?.();}
  function worldMutate(fn){if(!mutate(()=>{worldReceipt=fn();}))return;showWorld();$('#world-receipt')?.focus({preventScroll:true});dialog.scrollTop=0;if(state.phase==='ending'){modal(`${top('游历落定 · 此生终卷')}${heading(worldReceipt.title,worldReceipt.text)}${timeReceipt(worldReceipt)}${chips(worldReceipt.effects)}${receiptNotes(worldReceipt)}<button class="primary-button full-width" data-command="ending">展开此生结局 ${icon('arrow')}</button>`);}else toast(worldReceipt.title);}
  function passiveDetails(entry){const lines=[];for(const[id,effects]of Object.entries(entry.actions||{}))lines.push(`${find(D.actions,id)?.name||id}额外：${E.effectsText(effects)}`);if(entry.powerBonus)lines.push(`随行战力 +${entry.powerBonus}`);if(entry.breakthroughBonus)lines.push(`破境成功率 +${Math.round(entry.breakthroughBonus*100)} 个百分点`);return notes(lines,'passive-benefits');}
  function showCompanions(){const entries=D.companions.map(c=>({c,status:E.companionStatus(state,c.id)})),partner=entries.find(x=>x.status.isPartner);modal(`${worldHeading('道侣 · 相知相守，共问长生',partner?`与${partner.c.name}，同行这一程。`:'山海很大，总有同行的人。','交谈或赠礼增进情谊，满 18 岁、好感达到 60，双方相许后才可结为道侣。同一时间仅有一位道侣。')}<div class="world-note">每位修士每个日历年可交谈或赠礼一次，交往、结契与分别均消耗实际时间，跨年后相处机会刷新。道侣加成随缘同行，并解锁「同心共修」。伤害他人可能让正道道侣失望，好感归零会结束关系。</div><div class="companion-grid">${entries.map(({c,status})=>`<article class="companion-card ${status.isPartner?'bonded':''}"><div class="companion-top"><span class="companion-portrait">${esc(c.name.slice(0,1))}</span><div><h3>${esc(c.name)}</h3><span>${esc(c.gender)} · 成年修士 · ${esc(find(D.paths,c.path)?.name)}</span></div><b>${status.isPartner?'道侣':status.met?'已相识':'待结识'}</b></div><p>${esc(c.desc)}</p><div class="companion-require">相逢条件 · ${esc(D.realms[c.requireRealm].name)}及以上 · 善恶至少 ${c.minMorality}</div>${progress('情谊',status.affection,100,status.isPartner?'gold':'')}<details class="companion-benefits"><summary>结为道侣后的长期收益</summary>${passiveDetails(c)}<p>解锁共同行动，双方相伴期间生效。</p></details><div class="companion-actions">${status.actions.filter(a=>a.id!=='separate'||status.isPartner).filter(a=>a.id!=='bond'||!status.isPartner).map(a=>`<div><button class="${a.id==='bond'?'primary-button':'outline-button'}" data-companion="${esc(c.id)}" data-interaction="${esc(a.id)}" ${a.canDo?'':'disabled'}>${esc(a.label)}${a.cost?` · ${num(a.cost)} 灵石`:''}</button><span>耗时 ${esc(worldDuration(a.id,a))}</span>${!a.canDo?`<span>${esc(a.reason)}</span>`:''}</div>`).join('')}</div></article>`).join('')}</div>`,true);}
  function showAuction(){const lots=E.auctionStatus(state);modal(`${worldHeading('拍卖场 · 封价入匣，各凭眼力','一锤定音，灵物归谁？','每个日历年刷新三件拍品，各有一次封价机会。胜出支付自己的出价，落选不扣灵石；竞拍无论胜负都经过标注的月份。')}<div class="auction-wallet">可用灵石 <b>${num(state.stones)}</b><span>对手出价在显示区间内，封价前不可见。</span></div><div class="auction-grid">${lots.map(lot=>{const item=find(D.items,lot.itemId);return `<article class="auction-card ${lot.closed?'closed':''}"><div class="auction-item"><span class="item-icon">${icon(item?.icon||'gem')}</span><div><h3>${esc(lot.name)}</h3><span>本场 ${lot.quantity} 件 ${item?.auctionOnly?'· 拍卖专属':''}</span></div><b>${lot.closed?(lot.outcome==='won'?'竞得':'落选'):'封价待开'}</b></div><p>${esc(item?.desc)}</p>${item?itemDetails(item):''}<div class="auction-prices"><span>起拍价 <b>${num(lot.basePrice)}</b></span><span>对手估价 <b>${num(lot.rivalRange[0])}–${num(lot.rivalRange[1])}</b></span></div>${lot.closed?`<div class="auction-outcome ${lot.outcome==='won'?'won':''}">${lot.outcome==='won'?'灵物已收入行囊':'本场未能竞得'} · 成交价 ${num(lot.winningBid)} 灵石</div>`:`<form class="auction-form" data-auction-form="${esc(lot.id)}"><label for="bid-${esc(lot.id)}">你的封存出价 · 灵石</label><div><input id="bid-${esc(lot.id)}" data-auction-bid="${esc(lot.id)}" type="number" inputmode="numeric" min="${lot.minBid}" step="1" required value="${esc(bidDrafts[lot.id]??lot.minBid)}" ${lot.canBid?'':'disabled'}><button class="primary-button" type="submit" ${lot.canBid?'':'disabled'}>竞拍 · ${esc(worldDuration('auction',lot))}</button></div></form>${!lot.canBid?`<p class="world-card-reason">${esc(lot.reason)}</p>`:''}`}</article>`;}).join('')}</div><p class="shop-footnote">拍卖仅使用游戏内灵石。高境界解锁更多稀有拍品，装备与行囊持有上限同样适用。</p>`,true);}
  function dungeonReward(def){const lines=[];if(def.reward?.effects)lines.push(E.effectsText(def.reward.effects));for(const[id,n]of Object.entries(def.reward?.gainItems||{}))lines.push(`${find(D.items,id)?.name||id} ×${n}`);if(def.reward?.grantPerk)lines.push(`长久收获「${find(D.perks,def.reward.grantPerk)?.name||def.reward.grantPerk}」`);return lines.join('；');}
  function showDungeons(){const status=E.dungeonStatus(state),active=status.active;modal(`${worldHeading('秘境 · 三关寻道，进退由心','山门之外，另有一方天地。','入境与探关各有耗时，进度跨月、跨年保留。每处秘境此生只可通关一次；失败后下个日历年可再试。')}<div class="world-note">离开秘境即刻完成，不耗时间，也不退入境费用。谨慎探路风险较低；冒险深入收益更高，也更可能负伤。通关奖励会真实加入行囊或留下永久能力。</div>${active?`<section class="active-dungeon"><div class="section-top"><div><span class="eyebrow">当前秘境</span><h3>${esc(active.name)}</h3></div><span class="phase-pill">将探第 ${active.stage} / ${active.total} 关</span></div>${progress('已过关数',active.stage-1,active.total,'gold')}<p class="dungeon-risk">${esc(active.risk)}</p><p class="dungeon-reward">通关收获：${esc(active.rewardText)}</p><div class="dungeon-approaches"><button class="outline-button" data-dungeon-approach="careful" ${!active.carefulReason?'':'disabled'}><b>谨慎探路</b><span>成功率 ${Math.round(active.carefulChance*100)}% · ${esc(active.carefulDurationText||worldDuration('dungeonCareful'))}</span>${active.carefulReason?`<small>${esc(active.carefulReason)}</small>`:''}</button><button class="primary-button" data-dungeon-approach="bold" ${!active.boldReason?'':'disabled'}><b>冒险深入</b><span>成功率 ${Math.round(active.boldChance*100)}% · ${esc(active.boldDurationText||worldDuration('dungeonBold'))}</span>${active.boldReason?`<small>${esc(active.boldReason)}</small>`:''}</button></div>${!active.canExplore?`<p class="world-card-reason">${esc(active.reason)}</p>`:''}<div class="dungeon-exit"><button class="link-button" data-command="dungeon-leave">离开秘境 · 即刻 ${icon('arrow')}</button><button class="link-button" data-command="bag">整理行囊</button></div></section>`:''}<div class="dungeon-grid">${status.entries.map(entry=>{const def=find(D.dungeons,entry.id);return `<article class="dungeon-card ${entry.completed?'completed':''}"><div class="dungeon-card-top"><span>${icon('mountain')}</span><h3>${esc(def.name)}</h3><b>${entry.completed?'已通关':active?.id===entry.id?'正在探索':`${esc(D.realms[def.requireRealm].name)}起`}</b></div><p>${esc(def.desc)}</p><p class="dungeon-static-reward">基础通关奖励 · ${esc(dungeonReward(def))}</p><div class="dungeon-card-bottom"><span>入境费 <b>${num(def.entryCost)}</b> 灵石</span><button class="outline-button" data-dungeon-enter="${esc(entry.id)}" ${entry.canEnter?'':'disabled'}>${entry.completed?'已留传承':`踏入秘境 · ${esc(worldDuration('dungeonEnter',entry))}`}</button></div>${!entry.canEnter?`<p class="world-card-reason">${esc(entry.reason)}</p>`:''}${entry.attempts?`<p class="dungeon-history">已探索 ${entry.attempts} 次${entry.lastYear?` · 最近第 ${entry.lastYear} 年`:''} · ${esc(({completed:'通关',failed:'失利',abandoned:'离开',active:'探索中'})[entry.lastOutcome]||entry.lastOutcome||'已有留痕')}</p>`:''}</article>`;}).join('')}</div>`,true);}
  function showCombat(){const moral=E.moralityStatus(state);modal(`${worldHeading('论道台与山野 · 出手自有因果',combatMode==='spar'?'切磋高下，点到为止。':'山野争夺，也有代价。',combatMode==='spar'?'切磋消耗标注的月份，每位对手每个日历年限一次。切磋不会致命，还能积累善名。':'抢劫消耗标注的月份，每位对手每个日历年限一次。无论成败都会损失善恶；失手可能重伤或陨落。')}<div class="world-tabs" aria-label="对战方式"><button data-combat-mode="spar" class="${combatMode==='spar'?'selected':''}" aria-pressed="${combatMode==='spar'}">点到为止 · 切磋</button><button data-combat-mode="rob" class="${combatMode==='rob'?'selected evil-tab':''}" aria-pressed="${combatMode==='rob'}">山野争夺 · 抢劫</button></div><div class="combat-self"><span>自身战力 <b>${num(E.power(state))}</b></span><span>善恶 ${moral.value>0?'+':''}${moral.value} · ${esc(moral.title)}</span></div><div class="combat-grid">${D.opponents.map(opponent=>{const status=E.combatStatus(state,opponent.id,combatMode);return `<article class="combat-card ${combatMode==='rob'?'robbery':''}"><div class="combat-title"><span class="opponent-mark">${esc(opponent.name.slice(0,1))}</span><div><h3>${esc(opponent.name)}</h3><span>对方战力 ${num(status.opponentPower)}</span></div><b>${Math.round(status.chance*100)}%<small>获胜机会</small></b></div><p>${esc(opponent.desc)}</p><div class="combat-reward">所得 · ${esc(status.rewardText)}</div><div class="combat-risk">风险 · ${esc(status.risk)}</div><div class="combat-bottom"><span>善恶 ${status.moralityChange>0?'+':''}${status.moralityChange}<small>无论胜负</small></span><button class="${combatMode==='rob'?'danger-button':'outline-button'}" data-fight="${esc(opponent.id)}" ${status.canFight?'':'disabled'}>${combatMode==='spar'?'请教切磋':'出手抢劫'} · ${esc(worldDuration(combatMode,status))}</button></div>${!status.canFight?`<p class="world-card-reason">${esc(status.reason)}</p>`:''}</article>`;}).join('')}</div>`,true);}
  function worldArchive(){const moral=E.moralityStatus(state),partner=D.companions.find(c=>E.companionStatus(state,c.id).isPartner),completed=E.dungeonStatus(state).entries.filter(e=>e.completed);return `<section class="world-archive"><h3>天地间留下的回响</h3><div><span>善恶留名</span><b>${moral.value>0?'+':''}${moral.value} · ${esc(moral.title)}</b></div><div><span>相伴道侣</span><b>${esc(partner?.name||'此生独行')}</b></div><div><span>通关秘境</span><b>${completed.length} / ${D.dungeons.length}</b></div>${completed.length?`<p>${completed.map(e=>esc(find(D.dungeons,e.id)?.name)).join(' · ')}</p>`:''}</section>`;}
  function affinityLines(status){const lines=[];for(const[id,effects]of Object.entries(status.bonuses.actions||{}))lines.push(`${find(D.actions,id)?.name||id}：${E.effectsText(effects)}`);if(status.bonuses.breakthroughBonus)lines.push(`破境成功率 +${Math.round(status.bonuses.breakthroughBonus*100)} 个百分点`);return lines;}
  function affinityPathNames(rootId){return D.paths.filter(p=>(p.affinityRoots||[]).includes(rootId)).map(p=>p.name).join('、')||'无额外契合';}
  function affinityRootNames(path){return (path.affinityRoots||[]).map(id=>find(D.roots,id)?.name||id).join('、');}
  function pathProfile(){const status=E.pathStatus(state),technique=find(D.actions,status.techniqueId),root=E.rootStatus(state);return `<section class="path-profile ${status.matched?'matched':''}" aria-label="灵根与流派"><div class="path-profile-heading"><b>${esc(status.pathName)}道途</b><span>${status.matched?'灵根契合':'自成一脉'}</span></div><p class="root-current">${esc(root.name)} · 修为收益 ×${root.cultivationMultiplier} · 先天破境 ${root.breakthroughBonus>=0?'+':''}${Math.round(root.breakthroughBonus*100)} 个百分点</p><p>${status.matched?'灵根与道途相合，以下加成已计入行动预览。':esc(status.summary)}</p>${status.matched?notes(affinityLines(status),'affinity-details')+'<p class="affinity-cap">总破境成功率上限 95%。</p>':'<p class="affinity-neutral">仍保留灵根、流派的基础收益与专属修行。</p>'}${technique?`<div class="technique-note"><strong>专属 · ${esc(technique.name)}</strong><p>${esc(technique.desc)}</p><button class="link-button" data-jump="${esc(technique.id)}" ${state.phase==='ending'?'disabled':''}>查看专属修行 ${icon('arrow')}</button></div>`:''}</section>`;}
  function comboPreview(){const preview=birthPreview(),status=E.pathStatus(preview),technique=find(D.actions,status.techniqueId),root=E.rootStatus(preview);return `<section class="combo-preview ${status.matched?'matched':''}" aria-label="当前灵根流派组合"><div class="combo-heading"><div><span class="eyebrow">此生的修行方向</span><h3>${esc(root.gradeName)}<span>×</span>${esc(status.pathName)}</h3></div><span class="combo-match">${status.matched?'有契合灵根 · 获得额外加成':'自由组合 · 基础能力保留'}</span></div><p>${status.matched?'任一灵根元素与流派相合，即可获得下列额外收益。':esc(status.summary)}</p>${status.matched?`<div class="combo-bonuses">${affinityLines(status).map(t=>`<span>${esc(t)}</span>`).join('')}</div>`:'<p class="combo-neutral">仍能正常修炼、使用专属行动与突破。先天资质倍率照常生效。</p>'}<p class="affinity-cap">先天资质、契合、天赋和心境共同影响破境，总成功率上限 95%。</p>${technique?`<div class="combo-technique"><span>专属修行 · <b>${esc(technique.name)}</b></span><small>开局耗时 ${esc(E.actionTime(preview,technique.id).text)} · 已计入资质与当前天赋</small>${chips(E.actionPreview(preview,technique.id))}${notes(actionExtra(technique))}</div>`:''}</section>`;}
  function header() { return `<header class="site-header"><a class="brand" href="./" aria-label="仙之巅首页"><span class="brand-seal">仙</span><span>仙之巅<small>一念入山海 · 百转问长生</small></span></a><nav aria-label="游戏工具"><button class="text-button" data-command="help" aria-label="修行手札">${icon('help')}<span>修行手札</span></button><button class="text-button" data-command="saves" aria-label="存档管理">${icon('save')}<span>存档管理</span></button><button class="text-button" data-command="new" aria-label="重入轮回">${icon('refresh')}<span>重入轮回</span></button></nav></header>`; }
  function character() {
    const root = find(D.roots,state.root), path = find(D.paths,state.path), sect = find(D.sects,state.sect);
    return `<section class="panel character-panel"><div class="character-top"><span class="portrait" aria-hidden="true">${esc(state.name.slice(0,1))}</span><div><span class="eyebrow">山海间的一位修士</span><h1>${esc(state.name)}</h1><p>${esc(E.rootStatus(state).name)} · ${esc(path?.name)}</p></div></div><div class="character-time"><div><b class="${state.age>=100000?'long-number':''}">${state.age}</b><span>岁${E.timeStatus(state).ageMonths?` · ${E.timeStatus(state).ageMonths} 个月`: ' · 春秋'}</span></div><div><b class="${state.year>=100000?'long-number':''}">${state.year}</b><span>年 · 第 ${E.timeStatus(state).month} 月</span></div></div>${lifespanPanel()}<div class="body-stats">${progress('气血',state.health,100,state.health<25?'red':'')}${progress('心境',state.resolve,100,'gold')}</div><div class="ability-list"><div><span>悟性 <small>参悟与破境</small></span><b>${state.insight}</b></div><div><span>体魄 <small>战力与险境</small></span><b>${state.physique}</b></div><div><span>神识 <small>战力与识物</small></span><b>${state.spirit}</b></div><div><span>声望 <small>机缘与战力</small></span><b>${state.reputation}</b></div></div><div class="power-line"><span>${icon('sword')} 综合战力</span><b>${num(E.power(state))}</b></div><details class="small-details"><summary>战力、破境与寿元</summary><p>境界、体魄、神识和声望共同构成战力，装备、符箓与长期机缘也会加成。悟性与心境越高，突破境界的成功率越高。</p><p>行动按实际耗时推进年月，需要主动休整恢复气血与心境。气血归零或到达本境界寿限，会结束此生。</p>${lifespanTable()}</details><div class="talent-tags">${state.talents.map(id => { const t=find(D.talents,id); return `<span title="${esc(t?.desc)}" class="${t?.rarity==='rare'?'rare':''}">${esc(t?.name)}</span>`; }).join('')}</div>${pathProfile()}<div class="sect-line"><span>${icon('temple')}${esc(sect?.name || '尚未拜入山门')}</span><button class="link-button" data-command="sects">${sect?'详情':'拜访'} ${icon('arrow')}</button></div>${sect?`<div class="contribution">${esc(E.sectStatus(state).rank?.name||'外门弟子')} · 功勋 ${num(state.sectMerit||0)}<b>贡献 ${num(state.contribution)}</b></div>`:''}</section>`;
  }
  function bagPanel() {
    const items = D.items.filter(i => state.inventory[i.id] > 0), buffs = D.buffs.filter(b => state.buffs[b.id] > 0), conditions = D.conditions.filter(c => state.conditions.includes(c.id));
    return `<section class="panel bag-panel"><div class="section-top"><h2>${icon('bag')} 行囊</h2><button class="link-button" data-command="bag">打开 ${icon('arrow')}</button></div><div class="wallet"><div><span>灵石</span><b>${num(state.stones)}</b></div><button class="outline-button" data-command="shop">逛坊市 ${icon('arrow')}</button></div>${items.length?`<div class="bag-chips">${items.map(i=>`<button data-command="bag">${esc(i.name)} <b>×${state.inventory[i.id]}</b></button>`).join('')}</div>`:'<p class="muted small">一本心法、一柄灵剑，也许就是下一次破境的契机。</p>'}${buffs.map(b=>`<div class="status-note"><b>${esc(b.name)} · 剩余 ${esc(E.formatDuration(state.buffs[b.id]))}</b><p>${esc(b.desc)}</p></div>`).join('')}${conditions.map(c=>`<div class="status-note warning"><b>${esc(c.name)}</b><p>${esc(c.desc)}</p><button class="link-button" data-jump="rest">查看调养 ${icon('arrow')}</button></div>`).join('')}</section>`;
  }
  function realmPanel() {
    const realm=E.realmInfo(state), status=E.breakthroughStatus(state), next=D.realms[state.realm+1];
    return `<section class="panel realm-panel">${landscape}<div class="realm-intro"><div><span class="eyebrow">${realm.world==='immortal'?'仙界 · 继续问道':'凡界 · 此刻的道途'}</span><h2>${esc(realm.name)}<span>${esc(realm.subtitle)}</span></h2></div><span class="realm-mark" aria-hidden="true">${state.realm===D.realms.length-1?'圆满':'问道'}</span></div><ol class="realm-road" aria-label="修仙境界">${D.realms.map((r,i)=>`<li class="${i===state.realm?'current':i<state.realm?'passed':''}" ${i===state.realm?'aria-current="step"':''}><span>${String(i+1).padStart(2,'0')}</span>${esc(r.name)}</li>`).join('')}</ol>${next?`<div class="cultivation-row"><div class="cultivation-progress">${progress('修为积累',state.cultivation,status.threshold)}<p>${status.ready?`破境条件已具备 · 当前成功率 ${Math.round(status.chance*100)}%`:esc(status.reason)}<span>下一境 · ${esc(next.name)}</span></p><div class="lifespan-gain">${icon('sun')} ${esc(nextLifespanText())}</div></div><button class="primary-button breakthrough-button" data-action="breakthrough" ${E.actionError(state,'breakthrough')?'disabled':''}><span>尝试突破 ${icon('arrow')}</span><small>闭关 ${esc(E.actionTime(state,'breakthrough').text)}</small></button></div>`:'<p class="ascended-note">越过山海尽头，寿元无尽，这一段道途已圆满。</p>'}</section>`;
  }
  function timePanel(){const time=E.timeStatus(state);return `<section class="panel time-panel"><div><span class="eyebrow">${esc(time.dateText)} · ${esc(time.ageText)}</span><h2>此番修行，愿付几许光阴？</h2><p>每项行动立即进行，耗时与收益写在卡片上。闭关会随境界延长，修炼之后可能遇见机缘。</p></div>${state.phase==='event'?'<button class="primary-button" data-command="continue-report">处理眼前机缘 '+icon('arrow')+'</button>':state.phase==='ending'?'<button class="outline-button" data-command="ending">展开此生结局 '+icon('arrow')+'</button>':time.remainingMonths!==null&&time.remainingMonths<=1?'<button class="outline-button" data-command="wait-end">静候此生终卷</button>':`<span class="time-elapsed">已修行 <b>${esc(time.elapsedText)}</b></span>`}</section>`;}
  function actionExtra(a) { const parts=[]; for(const [id,n] of Object.entries(a.costItems||{}))parts.push(`消耗${find(D.items,id)?.name||id} ×${n}`);for(const [id,n] of Object.entries(a.gainItems||{}))parts.push(`获得${find(D.items,id)?.name||id} ×${n}`);if(a.clearCondition)parts.push(`解除${find(D.conditions,a.clearCondition)?.name||a.clearCondition}`);return parts; }
  function actionPanel(){const categories=['修行','山门','游历','生活'];return `<section class="action-section" id="action-section"><div class="action-heading"><h2>修行诸事</h2><div class="filters" aria-label="行动分类">${categories.map(c=>`<button data-filter="${c}" class="${filter===c?'selected':''}" aria-pressed="${filter===c}">${c}</button>`).join('')}</div></div><div class="action-grid">${D.actions.filter(a=>a.category===filter&&(!a.requirePath||a.requirePath===state.path)).sort((a,b)=>Number(Boolean(b.requirePath))-Number(Boolean(a.requirePath))).map(a=>{const error=E.actionError(state,a.id),effects=a.id==='breakthrough'?{}:E.actionPreview(state,a.id),extra=actionExtra(a),time=E.actionTime(state,a.id);return `<article class="action-card immediate-action ${error?'unavailable':''} ${a.requirePath?'path-action':''}">${a.requirePath?`<span class="exclusive-label">${esc(find(D.paths,state.path)?.name)}专属修行</span>`:''}<div class="action-title"><span class="action-symbol">${icon(a.icon)}</span><h3>${esc(a.name)}</h3></div><p>${esc(a.desc)}</p>${a.id==='breakthrough'?`<div class="action-outcome">当前成功率 ${Math.round(E.breakthroughStatus(state).chance*100)}% · 成败均经过闭关岁月</div>`:chips(effects)}${extra.length?`<div class="action-outcome">${extra.map(esc).join(' · ')}</div>`:''}<div class="action-duration">${icon('moon')} 耗时 <b>${esc(time.text)}</b>${a.realmTime?'<span>随境界延长</span>':''}</div><button class="primary-button perform-action" data-action="${esc(a.id)}" ${error?'disabled':''}>进行${esc(a.name)} ${icon('arrow')}</button><div class="action-foot ${error?'locked':''}">${esc(error||a.hint||'点击立即进行，按本次耗时结算')}</div></article>`;}).join('')}</div></section>`;}
  function storyRecords(all=false) {
    const stories=D.stories.map(s=>E.storyStatus(state,s.id)).filter(s=>s&&(all||s.status!=='active'));
    return stories.length?`<details class="story-history" ${all?'open':''}><summary>已走过的机缘 · ${stories.length} 段</summary>${stories.map(s=>`<div class="history-story"><div><b>${esc(s.name)}</b><span>${{active:'未完',completed:'圆满',abandoned:'放下'}[s.status]}</span></div><p>${esc(s.ending || `已完成 ${s.progress} / ${s.target} 次${s.actionName}`)}</p></div>`).join('')}</details>`:'';
  }
  function perksHTML() { return state.perks.length?`<div class="perks-list">${state.perks.map(id=>{const p=find(D.perks,id);return `<div><span class="tiny-seal">缘</span><p><b>${esc(p?.name)}</b><span>${esc(p?.desc)}</span></p></div>`;}).join('')}</div>`:''; }
  function storiesPanel(){const active=D.stories.map(s=>E.storyStatus(state,s.id)).filter(s=>s?.status==='active');return `<section class="panel stories-panel"><div class="section-top"><h2>${icon('scroll')} 尘缘未了</h2><span class="muted small">相逢，自有期限</span></div>${active.length?`<div class="story-grid">${active.map(s=>`<article class="story-card"><div class="story-top"><h3>${esc(s.name)}</h3><span>${s.ready?'等待后续':`余 ${esc(s.remainingText||E.formatDuration(s.remainingMonths))}`}</span></div><p>${esc(s.desc)}</p>${progress(s.actionName,s.progress,s.target,'gold')}<p class="story-deadline">截止 · 第 ${Math.floor(s.dueMonth/12)+1} 年 ${s.dueMonth%12+1} 月</p><p class="story-reward">圆满所得：${esc(s.rewardDesc)}</p><button class="link-button" data-jump="${esc(find(D.stories,s.id).actionId)}" ${s.ready||state.phase!=='planning'?'disabled':''}>查看${esc(s.actionName)} ${icon('arrow')}</button></article>`).join('')}</div>`:'<div class="empty-stories"><span class="empty-orbit" aria-hidden="true">缘</span><p>山海未远，相逢有时。<span>游历中可能遇见委托、秘闻与灵兽羁绊。接下后，需要在期限内用行动兑现。</span></p></div>'}${perksHTML()}${storyRecords()}</section>`;}
  function recentPanel(){const recent=state.lastAction||state.lastYear;return `<section class="panel chronicle-panel"><div class="section-top"><h2>${icon('book')} 仙途纪事</h2><span class="muted small">${state.log.length} 笔留痕</span></div>${recent?`<div class="last-growth"><div><b>${esc(state.lastAction?(recent.title||'最近一次修行'):'旧版修行记录')}</b><span>${state.lastAction?`经过 ${esc(E.formatDuration(recent.months||0))}`:`第 ${recent.year} 年`}</span></div>${chips(recent.effects)}${notes([...new Set([...(recent.changes||[]),...(recent.notes||[])])])}</div>`:''}${state.lastEvent?`<div class="last-encounter"><span class="tiny-seal">遇</span><div><b>${esc(state.lastEvent.title)}</b><p>${esc(state.lastEvent.result)}</p>${chips(state.lastEvent.effects)}${notes(state.lastEvent.changes)}</div></div>`:''}<details class="chronicle" ${state.log.length<5?'open':''}><summary>翻阅修行年表</summary>${state.log.length?`<ol>${state.log.map(l=>`<li><span>${l.elapsedMonths!==undefined?`第 ${Math.floor(l.elapsedMonths/12)+1} 年 ${l.elapsedMonths%12+1} 月`:`第 ${l.year} 年${l.month?' '+l.month+' 月':''}`}</span><p>${esc(l.text)}</p></li>`).join('')}</ol>`:'<p class="muted small">第一行，留待你落笔。</p>'}</details></section>`;}
  function render() {
    if(!state){$('#app').innerHTML=`<div class="app-shell">${header()}<main class="empty-start">${landscape}<span class="intro-seal">山海问道</span><p class="eyebrow">文字修仙 · 破境求长生</p><h1>山中无日月，<br>此生有回响。</h1><p>承灵根，修心境。踏过人间烟火，问一问长生。</p><button class="primary-button" data-command="new">开启一段仙途 ${icon('arrow')}</button>${loadError?`<p class="load-error">${esc(loadError)}</p>`:''}</main>${footer()}</div>`;return;}
    $('#app').innerHTML=`<div class="app-shell">${header()}<div class="page-caption"><span>山海历 · ${esc(E.timeStatus(state).dateText)}</span><span>${state.phase==='ending'?'此生已成卷':saveOK?'落子无悔，进度已自动留存':'请导出存档以保存进度'}</span></div><main class="game-layout"><aside class="sidebar">${character()}${bagPanel()}</aside><div class="main-column">${realmPanel()}${timePanel()}${worldPanel()}${state.phase!=='ending'?actionPanel():`<section class="panel ending-callout"><span class="intro-seal">此生</span><div><h2>${esc(state.ending?.title || '仙途成卷')}</h2><p>${esc(state.ending?.desc)}</p></div><button class="outline-button" data-command="ending">展开仙途长卷 ${icon('arrow')}</button></section>`}${storiesPanel()}${recentPanel()}</div></main>${footer()}</div>`;
    const realmRoad=$('.realm-road'),currentRealm=$('.realm-road .current');if(realmRoad&&currentRealm)realmRoad.scrollLeft=Math.max(0,currentRealm.offsetLeft-realmRoad.clientWidth/2+currentRealm.clientWidth/2);
  }
  function footer(){return '<footer class="site-footer"><span>仙之巅 <i>·</i> 山海间，写自己的道</span><span>XIAN ZHI DIAN · v3.0.0</span></footer>';}
  function randomSeed(){try{return crypto.getRandomValues(new Uint32Array(1))[0]||1;}catch(_){return (Date.now() ^ Math.floor(Math.random()*0xffffffff))>>>0||1;}}
  function newGame(){const birthSeed=randomSeed(),talentSeed=randomSeed(),root=E.drawRoot(birthSeed);draft={name:'无名',path:D.paths[0].id,talents:[],birthSeed,talentSeed,...root,pool:E.drawTalents(talentSeed,8),rerolls:2};showNew();}
  function draftEffects(entry){const parts=[];if(Object.keys(entry.start||{}).length)parts.push(E.effectsText(entry.start));for(const [id,effects] of Object.entries(entry.actions||{}))parts.push(`${find(D.actions,id)?.name||id}：${E.effectsText(effects)}`);if(entry.breakthroughBonus)parts.push(`破境成功率 +${Math.round(entry.breakthroughBonus*100)}%`);return parts.join('；');}
  function showNew(){const preview=birthPreview(),chosenPath=find(D.paths,draft.path),paths=D.paths.map(p=>{const recommended=(p.affinityRoots||[]).some(id=>draft.rootElements.includes(id)),technique=find(D.actions,p.technique);return `<button class="path-choice ${draft.path===p.id?'selected':''} ${recommended?'recommended':''}" data-path="${esc(p.id)}" aria-pressed="${draft.path===p.id}"><div class="path-choice-top"><span class="path-icon">${icon(p.icon||'compass')}</span><strong>${esc(p.name)}</strong>${recommended?'<span class="recommended-tag">灵根契合</span>':''}</div><p>${esc(p.desc)}</p><small>${esc(draftEffects(p))}</small><div class="path-affinities">契合灵根 · ${esc(affinityRootNames(p))}</div><div class="path-technique">专属修行 · <b>${esc(technique?.name||'随道途领悟')}</b></div></button>`;}).join('');modal(`${top('卷首 · 天赋因缘，落地生根')}${heading('天地之间，你是何人？','灵根随机天定，流派由你选择。资质有高下，山海间仍有自己的路。')}${state?'<div class="notice">开始新仙途将替换当前进度。想留住这一世，可先关闭弹窗，到「存档管理」导出备份。</div>':''}${loadError?`<div class="notice">${esc(loadError)}</div>`:''}<div class="new-name"><label for="character-name">道号</label><input id="character-name" maxlength="16" value="${esc(draft.name)}" placeholder="给自己取个道号" autocomplete="off"><span>最多 16 字</span></div><section class="creation-section"><div class="creation-title"><h3><span>壹</span> 先天灵根</h3><span>此生随机，不能手选</span></div>${rootDetails(preview)}<details class="root-grade-guide"><summary>了解天灵根、异灵根与多灵根资质</summary><div>${D.rootGrades.filter(g=>g.weight>0).map(g=>`<article><b>${esc(g.name)} <small>出现权重 ${g.weight}%</small></b><p>${esc(g.desc)}</p><span>修为 ×${g.cultivationMultiplier} · 破境 ${g.breakthroughBonus>=0?'+':''}${Math.round(g.breakthroughBonus*100)} 个百分点</span></article>`).join('')}</div></details></section><section class="creation-section"><div class="creation-title"><h3><span>贰</span> 心之所向</h3><span>所选流派 · ${esc(chosenPath.name)}</span></div><p class="recommendation-hint">任一先天元素与流派相合，就能触发契合。基础收益、资质和耗时均在下方预览中说明。</p><div class="path-grid expanded-paths">${paths}</div>${comboPreview()}</section><section class="creation-section"><div class="creation-title"><h3><span>叁</span> 命中天赋 <small>已选 ${draft.talents.length} / 2</small></h3><button class="link-button" data-command="reroll" ${draft.rerolls?'':'disabled'}>${icon('refresh')} 重抽天赋 · 余 ${draft.rerolls} 次</button></div><div class="talent-grid">${draft.pool.map(id=>{const t=find(D.talents,id);return `<button class="talent-choice ${draft.talents.includes(id)?'selected':''} ${t.rarity==='rare'?'rare':''}" data-talent="${esc(id)}" aria-pressed="${draft.talents.includes(id)}"><div><strong>${esc(t.name)}</strong><span>${t.rarity==='rare'?'稀有':'天赋'}</span></div><p>${esc(t.desc)}</p><small>${esc(draftEffects(t))}</small></button>`;}).join('')}</div></section><div class="creation-bottom"><p>天赋抽 8 选 2，重抽天赋不会改变灵根。<br>从十六岁起，在真实流逝的年月里修行。</p><button class="primary-button" data-command="start" ${draft.talents.length!==2?'disabled':''}>开始这段仙途 ${icon('arrow')}</button></div>`,true);}
  function showActionReceipt(report){if(!report){showPhase();return;}modal(`${top('一番修行 · 岁月已有回响')}${heading(report.title||'修行落定',report.text||'这一程的修行，已经写入仙途。')}${timeReceipt(report)}<div class="report-effects">${chips(report.effects)}</div>${receiptNotes(report)}<div class="report-summary"><span>当前境界</span><strong>${esc(E.realmInfo(state).name)}</strong><span>当前年龄</span><strong>${esc(E.timeStatus(state).ageText)}</strong></div><button class="primary-button full-width" data-command="continue-report">${state.phase==='ending'?'展开此生长卷':state.phase==='event'?'看看眼前机缘':'继续修行'} ${icon('arrow')}</button>`);}
  function performAction(id){let result;if(mutate(()=>{result=E.performAction(state,id);}))showActionReceipt(result);}
  function consequences(choice){return notes(E.consequencesText(state,choice),'choice-consequences');}
  function showEvent(){const event=find(D.events,state.pendingEvent);if(!event)return;modal(`${top(`${E.timeStatus(state).dateText} · 山海机缘`)}<div class="event-emblem">${icon(event.icon || 'compass')}</div>${heading(event.title,event.body)}<div class="event-choices">${event.choices.map((c,i)=>{const error=E.choiceError(state,c);return `<div class="event-choice ${error?'choice-locked':''}"><button data-choice="${i}" ${error?'disabled':''}><span class="choice-index">${['甲','乙','丙','丁'][i]||i+1}</span><b>${esc(c.text)}</b>${icon('arrow')}</button>${chips(c.effects)}${consequences(c)}${c.check?`<div class="check-preview"><span>以${esc(c.check.stat==='power'?'战力':E.labels[c.check.stat]||c.check.stat)}应对 · 当前成功率 <b>${Math.round(E.checkChance(state,c.check)*100)}%</b></span><details><summary>查看两种可能</summary><div><b>若成功</b><p>${esc(c.check.success.result)}</p>${chips(c.check.success.effects)}${consequences(c.check.success)}</div><div><b>若未成</b><p>${esc(c.check.failure.result)}</p>${chips(c.check.failure.effects)}${consequences(c.check.failure)}</div></details></div>`:''}${error?`<p class="choice-error">${esc(error)}</p>`:''}</div>`;}).join('')}</div>`);}
  function showResult(){const r=state.lastEvent;if(!r){showPhase();return;}modal(`${top('机缘落定 · 所行皆有回响')}<div class="result-seal">${r.outcome==='success'?'成':r.outcome==='failure'?'悟':'缘'}</div>${heading(r.title,r.result)}${chips(r.effects)}${notes(r.changes,'report-notes')}<button class="primary-button full-width" data-command="next">${state.phase==='ending'?'查看此生结局':'继续修行 · '+E.timeStatus(state).dateText} ${icon('arrow')}</button>`);}
  function showPhase(){if(state?.phase==='event')showEvent();else if(state?.phase==='ending')showEnding();}
  function showEnding(){if(!state?.ending)return;const end=state.ending;modal(`${top('终卷 · 山海记得来路')}<div class="ending-symbol">${icon(end.id==='emperor'?'sun':'mountain')}</div>${heading(end.title,`${state.name}，${end.desc}`)}<div class="ending-grid"><div><b>${esc(E.realmInfo(state).name)}</b><span>此生境界</span></div><div><b class="ending-age">${esc(E.timeStatus(state).ageText)}</b><span>岁月春秋</span></div><div><b>${state.breakthroughs}</b><span>成功破境</span></div><div><b>${num(E.power(state))}</b><span>最终战力</span></div></div><div class="ending-note">万种道途，未必都要通向同一个终点。你所相逢的人与事，已经成为这一生。</div>${worldArchive()}${storyRecords(true)}${perksHTML()}<div class="dialog-bottom"><button class="outline-button" data-command="export">留存此生</button><button class="primary-button" data-command="new">重入轮回 ${icon('refresh')}</button></div>`,true);}
  function itemDetails(item){const lines=[];for(const [id,effects] of Object.entries(item.actions||{}))lines.push(`${find(D.actions,id)?.name||id}额外：${E.effectsText(effects)}`);if(item.powerBonus)lines.push(`持有时战力 +${item.powerBonus}`);if(item.useEffects)lines.push(`使用后：${E.effectsText(item.useEffects)}`);if(item.buff){const b=find(D.buffs,item.buff);if(b)lines.push(`${b.name} · 持续 ${E.formatDuration(b.duration)}：${b.desc}`);}if(item.clearCondition)lines.push(`解除${find(D.conditions,item.clearCondition)?.name||item.clearCondition}`);for(const a of D.actions.filter(a=>a.requireItem===item.id))lines.push(`持有后解锁「${a.name}」`);return notes(lines,'item-details');}
  function showShop(){
    const owned=D.items.filter(i=>state.inventory[i.id]>0),list=shopTab==='goods'?D.items.filter(i=>!i.auctionOnly):owned;
    modal(`${top('坊市 · 灵物有价，机缘无价')}${heading(shopTab==='goods'?'山脚有一座小坊市。':'把机缘，收入行囊。','装备持有即生效；丹药与符箓在背包中使用。善恶会影响坊市价格，拍卖专属灵物需去拍卖场寻觅。')}<div class="shop-toolbar"><div class="shop-tabs"><button data-shop-tab="goods" class="${shopTab==='goods'?'selected':''}">坊市灵物</button><button data-shop-tab="bag" class="${shopTab==='bag'?'selected':''}">我的行囊 <span>${owned.length}</span></button></div><div class="shop-balance">${icon('gem')}<span>灵石</span><b>${num(state.stones)}</b></div></div>${receipt?`<section class="receipt" role="status"><b>${esc(receipt.title)}</b><p>${esc(receipt.text)}</p>${chips(receipt.effects)}${notes(receipt.changes)}</section>`:''}${!list.length?'<div class="empty-bag"><span class="empty-orbit">囊</span><p>行囊尚空。可去坊市添置灵物，或安排采药、采矿。</p></div>':`<div class="shop-grid">${list.map(item=>{const status=E.itemStatus(state,item.id);return `<article class="shop-item"><div class="shop-item-top"><span class="item-icon">${icon(item.icon)}</span><div><h3>${esc(item.name)}</h3><span>${item.kind==='equipment'?'随身装备':item.useEffects||item.buff||item.clearCondition?'消耗灵物':'炼制材料'} · 持有 ${status.owned} / ${item.max}</span></div>${shopTab==='goods'?`<b>${num(status.price)}<small>灵石</small></b>`:''}</div><p>${esc(item.desc)}</p>${itemDetails(item)}<div class="shop-item-bottom">${shopTab==='goods'?`<button class="outline-button" data-buy="${esc(item.id)}" ${status.canBuy?'':'disabled'}>购入一件 ${icon('plus')}</button>${!status.canBuy?`<span>${esc(status.buyReason)}</span>`:''}`:`<button class="outline-button" data-use="${esc(item.id)}" ${status.canUse?'':'disabled'}>${item.kind==='equipment'?'已随身生效':'使用一件'}</button><span>${esc(status.canUse?'使用后立即生效':status.useReason)}</span>`}</div></article>`;}).join('')}</div>`}<p class="shop-footnote">灵石仅为游戏内资源。买卖与使用即刻完成，不消耗月份；相同持续效果生效时不可重复使用。</p>`,true);
  }
  function openShop(tab='goods'){if(!state){toast('先开启一段仙途，再去坊市走走。');return;}shopTab=tab;receipt=null;showShop();}
  function showSects(){if(!state)return;const current=find(D.sects,state.sect),facility=find(D.facilities,sectTab),moral=E.moralityStatus(state);const admissions=`${sectRankCard()}<div class="sect-grid expanded-sects">${D.sects.map((sect,i)=>{const error=E.sectError(state,sect.id),selected=state.sect===sect.id,transfer=Boolean(current)&&!selected;return `<article class="sect-card ${selected?'selected':''}"><span class="sect-number">${String(i+1).padStart(2,'0')}</span><h3>${esc(sect.name)}</h3><span class="sect-tier">${esc(sect.tierLabel||'山门')} · ${esc(D.realms[sect.requireRealm].name)}起</span><p>${esc(sect.desc)}</p>${passiveDetails(sect)}${sect.shopDiscount?`<p class="small">坊市价格优惠 ${Math.round(sect.shopDiscount*100)}%</p>`:''}<button class="outline-button" data-sect="${esc(sect.id)}" ${error?'disabled':''}>${selected?'已入此门':transfer?'改投此门':'拜入此门'}${selected?'':` · ${esc(worldDuration('sectJoin'))}`}</button>${transfer&&!error?'<p class="transfer-short">换门后贡献、功勋和职务重新积累。</p>':''}${error?`<p class="small muted">${esc(error)}</p>`:''}</article>`;}).join('')}</div><div class="notice">宗门有各自的入门境界要求。可以改投入门境界更高的宗门，换门需 ${esc(worldDuration('sectJoin'))}，当前贡献余额、累计功勋和职务会清零，已获得物品与传承保留。善恶降至 -60 及以下时，新拜师与宗门设施会关闭。</div>`;const offers=facility?`<p class="facility-description">${esc(facility.desc)} · 兑换即刻完成。</p><div class="facility-grid">${facility.offers.map(offer=>{const status=E.facilityStatus(state,facility.id,offer.id),rank=find(D.sectRanks,offer.requireRank);return `<article class="facility-offer"><div><h3>${esc(offer.name)}</h3><b>${num(status.cost)}<small>贡献</small></b></div><p>${esc(offer.desc)}</p>${offer.requireRealm!==undefined?`<span class="facility-realm">自身境界 · ${esc(D.realms[offer.requireRealm].name)}及以上</span>`:''}${rank?`<span class="facility-realm">宗门职务 · ${esc(rank.name)}及以上</span>`:''}${offer.requireSectRealm!==undefined?`<span class="facility-realm">所属宗门入门境界 · ${esc(D.realms[offer.requireSectRealm].name)}及以上</span>`:''}${chips(offer.effects)}${notes(E.consequencesText(state,offer))}<button class="outline-button" data-facility="${esc(facility.id)}" data-offer="${esc(offer.id)}" ${status.canExchange?'':'disabled'}>以贡献兑换 · 即刻</button>${!status.canExchange?`<p class="world-card-reason">${esc(status.reason)}</p>`:''}</article>`;}).join('')}</div>`:'';modal(`${worldHeading('宗门 · 入门有阶，立功有位',current?`${current.name}，此间修行与担当。`:'山门各有道，择一而入。','境界决定能进哪座山门，功勋与境界共同决定职务晋升。更高职务带来额外收益与新行动。')}<div class="facility-wallet"><span>贡献余额 <b>${num(state.contribution)}</b></span><span>累计功勋 ${num(state.sectMerit||0)} · ${esc(moral.title)}</span></div><div class="world-tabs facility-tabs" aria-label="宗门设施"><button data-sect-tab="admission" class="${sectTab==='admission'?'selected':''}" aria-pressed="${sectTab==='admission'}">师承与职务</button>${D.facilities.map(f=>`<button data-sect-tab="${esc(f.id)}" class="${sectTab===f.id?'selected':''}" aria-pressed="${sectTab===f.id}">${esc(f.name)}</button>`).join('')}</div>${facility?offers:admissions}`,true);}
  function joinSect(id){if(state.sect&&state.sect!==id){const next=find(D.sects,id),current=find(D.sects,state.sect);modal(`${top('改投山门 · 辞旧入新')}${heading(`从${current.name}，转投${next.name}？`,`改投耗时 ${worldDuration('sectJoin')}。确认前，请看清即将放下与保留的经历。`)}<div class="transfer-warning"><h3>从新山门的外门弟子重新起步</h3><p>当前贡献余额 ${num(state.contribution)}、累计功勋 ${num(state.sectMerit||0)} 和宗门职务会归零。已经取得的物品、装备与长期传承会保留。</p></div><div class="dialog-bottom"><button class="outline-button" data-command="back-sects">暂不改投</button><button class="primary-button" data-confirm-sect="${esc(id)}">确认改投 · ${esc(worldDuration('sectJoin'))}</button></div>`);return;}worldMutate(()=>E.joinSect(state,id));}
  function help(){modal(`${top('修行手札 · 光阴有价，道途无穷')}${heading('一场修行，付一段真实岁月。')}<div class="help-grid"><section><span>01</span><h3>灵根天定，流派自选</h3><p>每次出生随机获得天灵根、异灵根、双灵根、三灵根或杂灵根。灵根元素与资质无法手选；重抽天赋也不会改变灵根。开局展示真实修为倍率与破境加成，正式角色与预览一致。</p><p>任一灵根元素与流派契合，可额外获得静室修炼修为 +4、专属修行修为 +6、破境成功率 +4 个百分点。正向行动修为再计入先天资质倍率，行动卡显示最终预计变化。</p></section><section><span>02</span><h3>点击行动，岁月即时流转</h3><p>每次点击「进行」即执行一项行动。行动卡会提前显示耗时、资源和预计收益。修炼与闭关随境界延长，凡间营生与其他行动各有自己的耗时。结果只结算这一次收益，耗时几个月不等于领取几次奖励。</p><p>岁月按真实月份推进；日期、年龄、剩余寿元同时更新。没有年末自动恢复，需要疗伤与休整时，请主动选择相应行动或用品。</p></section><section><span>03</span><h3>破境，需要在寿限前收功</h3><p>修为足够，且气血、心境至少 20，就可尝试突破。悟性、心境、资质、流派、职务、山门与丹药会影响成功率，总上限 95%。突破失败仍会经过整段闭关时间，并失去部分修为、气血与心境。</p><p>行动必须严格在当前寿元耗尽之前完成，不能靠一次来不及结束的突破续命。突破成功提高寿元上限；真仙飞升后继续修行，直至仙帝圆满。</p></section><section><span>04</span><h3>时光流逝，寿限仍在</h3><p>从十六岁开始，每经过十二个月长一岁。行动减少的是尚余时光，不会降低本境界的寿元上限。剩余不超过十年会提醒；仅余一个月、已无法行动时，可选择静候终卷。</p>${lifespanTable()}</section><section><span>05</span><h3>丹药与机缘，也有期限</h3><p>普通买卖、使用物品、事件选择和宗门兑换即刻完成。持续增益按经过的月份消退，开始行动时的收益会计入本次预览。背包会显示准确剩余年月。</p><p>连续故事按真实月份推进，任务进度与截止日期会显示在面板。行动后可能出现奇遇；目标完成或截止时会优先出现故事后续。不是每次行动都会发生随机事件。</p></section><section><span>06</span><h3>境界进山门，功勋升职务</h3><p>宗门各有入门境界。拜师或改投耗时 ${esc(worldDuration('sectJoin'))}，职务由外门弟子逐步晋升。晋升要求达到下一职务的境界和累计功勋，耗时 ${esc(worldDuration('promotion'))}，不花贡献余额。</p><p>功勋记录当前宗门累计获得的正向贡献，兑换物品不会降低功勋。仅可改投入门境界更高的宗门；确认后贡献余额、功勋与职务归零，物品和长期传承保留。</p></section><section><span>07</span><h3>游历按耗时，相逢看历年</h3><p>天地游历直接推进时间，交谈、赠礼、结契、拍卖与交战通常各耗一个月；进入秘境和每关也各有耗时。所有按钮会列出这一次的时间代价。</p><p>拍卖品及每位同道的年度相处、每位对手每种模式的交手限制，依真实日历跨年刷新。页面会显示下次刷新日期，秘境进度和道侣关系会跨年保留。</p></section><section><span>08</span><h3>相知以后，再互许同行</h3><p>交谈增加 12 情谊；赠礼花费 60 灵石增加 20。同一人每年可交谈或赠礼一次。满 18 岁、情谊达到 60，双方相许后才可结为道侣，同一时间只可有一位。结契与分别也各有耗时。</p><p>道侣带来长期收益并解锁同心共修。抢劫可能让正道道侣疏远，好感归零会分开。角色始终有各自的修行与去留意愿。</p></section><section><span>09</span><h3>秘境三关，慢行或冒进</h3><p>入境耗时 ${esc(worldDuration('dungeonEnter'))}；每关谨慎探路 ${esc(worldDuration('dungeonCareful'))}，冒险深入 ${esc(worldDuration('dungeonBold'))}。每次探索都可能受伤，界面会列出成功率与风险。进度可跨年月保存，一生只能取得一次完整传承。</p><p>失败后下一年再试，主动离开即刻完成、不退入境费。最终奖励放不进行囊时，可以先整理用品或离开。</p></section><section><span>10</span><h3>一份封价，善恶一念</h3><p>拍卖每件仅能出价一次，竞得支付自己的报价，落选不扣灵石；两种结果都经过竞拍时间。切磋不会致命且善恶 +2；抢劫无论胜败善恶 -18，失手可能重伤或陨落。</p><p>善恶至少 20 时坊市优惠 5%，-20 及以下加价 15%，-60 及以下不能新拜师或使用宗门设施。行善可以修复名声，人物卡显示当前评价。</p></section><section><span>11</span><h3>把时间与选择留在行卷</h3><p>进度自动保存在当前浏览器，不上传。换设备前可导出存档，导入后继续同一年月。旧档会自动适配新机制；以前尚未执行的计划不会扣资源，已有灵根、经历与物品会保留。</p></section></div><div class="notice">本作是虚构的修仙文字世界，灵石、丹药与命运都属于游戏。</div><button class="primary-button" data-command="close">收起手札，继续修行 ${icon('arrow')}</button>`,true);}
  function saves(){modal(`${top('留卷 · 让这段仙途有迹可寻')}${heading('山河很远，先留个备份。','进度仅保存在当前浏览器。导出后，可在另一台设备导入继续修行。')}${state?`<div class="save-summary"><span class="portrait small-portrait">${esc(state.name.slice(0,1))}</span><div><b>${esc(state.name)}</b><p>${esc(E.realmInfo(state).name)} · ${esc(E.timeStatus(state).dateText)} · ${esc(E.timeStatus(state).ageText)}</p></div></div>`:'<p class="notice">尚未开启新仙途，可以在这里导入之前的备份。</p>'}<div class="dialog-bottom"><button class="outline-button" data-command="import">导入存档</button><button class="primary-button" data-command="export" ${state?'':'disabled'}>导出当前仙途 ${icon('save')}</button></div>`);}
  function exportSave(){if(!state)return;const blob=new Blob([JSON.stringify({format:'XIUXIAN-LIFE',savedAt:new Date().toISOString(),state},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`xian-zhi-dian-Y${state.year}-M${E.timeStatus(state).month}.json`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('仙途已导出，请妥善保管。');}
  function mutate(fn){try{fn();save();render();return true;}catch(error){toast(error.message||'这一步暂时无法完成。');return false;}}
  function jump(id){const action=find(D.actions,id);if(!action)return;filter=action.category;close();render();$('#action-section')?.scrollIntoView({behavior:'smooth',block:'start'});document.querySelector(`[data-action="${CSS.escape(id)}"]`)?.focus({preventScroll:true});}
  const commands={close,new:newGame,help,saves,shop:()=>openShop(),bag:()=>openShop('bag'),sects:()=>openWorld('facilities'),ending:showEnding,'back-sects':showSects,promote:()=>worldMutate(()=>E.promoteSect(state)),'dungeon-leave':()=>worldMutate(()=>E.leaveDungeon(state)),export:exportSave,import:()=>$('#import-file').click(),'continue-report':()=>{close();showPhase();},next:()=>{close();showPhase();},'wait-end':()=>{const time=E.timeStatus(state);if(state.phase!=='planning'||time.remainingMonths===null||time.remainingMonths>1)return;modal(`${top('留卷 · 静候山风')}${heading('是否静候此生终卷？',`尚余 ${E.formatDuration(time.remainingMonths)}，已不足以完成新的行动。确认后度过最后的时光，不会获得额外修行收益。`)}<div class="dialog-bottom"><button class="outline-button" data-command="close">再看看行囊</button><button class="primary-button" data-command="confirm-wait">静候终卷</button></div>`);},'confirm-wait':()=>{if(mutate(()=>E.waitToEnd(state)))showEnding();},reroll:()=>{if(!draft?.rerolls)return;draft.talentSeed=randomSeed();draft.pool=E.drawTalents(draft.talentSeed,8);draft.talents=[];draft.rerolls--;const scroll=dialog.scrollTop;showNew();dialog.scrollTop=scroll;},start:()=>{if(!draft||draft.talents.length!==2)return;try{state=E.create({name:draft.name.trim()||'无名',path:draft.path,talents:draft.talents,seed:draft.birthSeed});loadError='';filter='修行';save();close();render();toast('先天灵根已定，从十六岁开始修行。');}catch(error){toast(error.message);}}};
  document.addEventListener('input',event=>{if(event.target.id==='character-name'&&draft)draft.name=event.target.value;if(event.target.dataset?.auctionBid)bidDrafts[event.target.dataset.auctionBid]=event.target.value;});
  document.addEventListener('submit',event=>{const form=event.target.closest('[data-auction-form]');if(!form)return;event.preventDefault();const input=form.querySelector('input[data-auction-bid]'),bid=Number(input.value);if(!Number.isSafeInteger(bid)||bid<1){toast('请填写正整数灵石出价。');input.focus();return;}worldMutate(()=>E.bidAuction(state,form.dataset.auctionForm,bid));});
  document.addEventListener('click',event=>{
    const b=event.target.closest('button');if(!b||b.disabled)return;
    if(b.dataset.command){commands[b.dataset.command]?.();return;}
    if(b.dataset.world){openWorld(b.dataset.world);return;}
    if(b.dataset.sectTab){sectTab=b.dataset.sectTab;worldReceipt=null;showSects();document.querySelector(`[data-sect-tab="${CSS.escape(sectTab)}"]`)?.focus({preventScroll:true});return;}
    if(b.dataset.facility){worldMutate(()=>E.exchangeFacility(state,b.dataset.facility,b.dataset.offer));return;}
    if(b.dataset.companion){worldMutate(()=>E.interactCompanion(state,b.dataset.companion,b.dataset.interaction));return;}
    if(b.dataset.dungeonEnter){worldMutate(()=>E.enterDungeon(state,b.dataset.dungeonEnter));return;}
    if(b.dataset.dungeonApproach){worldMutate(()=>E.exploreDungeon(state,b.dataset.dungeonApproach));return;}
    if(b.dataset.combatMode){combatMode=b.dataset.combatMode;worldReceipt=null;showCombat();document.querySelector(`[data-combat-mode="${CSS.escape(combatMode)}"]`)?.focus({preventScroll:true});return;}
    if(b.dataset.fight){worldMutate(()=>E.fight(state,b.dataset.fight,combatMode));return;}
    if(b.dataset.path){draft.path=b.dataset.path;const scroll=dialog.scrollTop;showNew();dialog.scrollTop=scroll;document.querySelector(`[data-path="${CSS.escape(draft.path)}"]`)?.focus({preventScroll:true});return;}
    if(b.dataset.talent){const id=b.dataset.talent;if(draft.talents.includes(id))draft.talents=draft.talents.filter(t=>t!==id);else if(draft.talents.length<2)draft.talents.push(id);else{toast('已选择两项天赋，先取消一项再更换。');return;}const scroll=dialog.scrollTop;showNew();dialog.scrollTop=scroll;document.querySelector(`[data-talent="${CSS.escape(id)}"]`)?.focus({preventScroll:true});return;}
    if(b.dataset.filter){filter=b.dataset.filter;render();document.querySelector(`[data-filter="${CSS.escape(filter)}"]`)?.focus({preventScroll:true});return;}
    if(b.dataset.action){performAction(b.dataset.action);return;}
    if(b.dataset.choice!==undefined){if(mutate(()=>E.choose(state,Number(b.dataset.choice))))showResult();return;}
    if(b.dataset.jump){jump(b.dataset.jump);return;}
    if(b.dataset.shopTab){shopTab=b.dataset.shopTab;receipt=null;showShop();return;}
    if(b.dataset.buy){const scroll=dialog.scrollTop;if(mutate(()=>{receipt=E.buyItem(state,b.dataset.buy);})){showShop();dialog.scrollTop=scroll;toast(receipt.title);}return;}
    if(b.dataset.use){if(mutate(()=>{receipt=E.useItem(state,b.dataset.use);})){showShop();toast(receipt.title);}return;}
    if(b.dataset.sect){joinSect(b.dataset.sect);return;}
    if(b.dataset.confirmSect){worldMutate(()=>E.joinSect(state,b.dataset.confirmSect));return;}
  });
  $('#import-file').addEventListener('change',async event=>{const file=event.target.files[0];event.target.value='';if(!file)return;try{if(file.size>1000000)throw Error('存档文件过大，请选择本游戏导出的文件');const raw=JSON.parse(await file.text());if(raw.format!=='XIUXIAN-LIFE')throw Error('这不是仙之巅的存档');const incoming=E.validate(raw.state);modal(`${top('导入仙途 · 确认接续')}${heading(`继续${incoming.name}的仙途？`,`${E.timeStatus(incoming).dateText} · ${E.timeStatus(incoming).ageText} · ${E.realmInfo(incoming).name}`)}<div class="notice">确认后会替换当前浏览器中的仙途进度。需要保留当前人生，请先取消并导出。</div><div class="dialog-bottom"><button class="outline-button" data-command="close">取消</button><button class="primary-button" id="confirm-import">确认导入</button></div>`);$('#confirm-import').addEventListener('click',()=>{state=incoming;filter='修行';loadError='';save();close();render();showPhase();toast('存档已导入，仙途可以继续。');},{once:true});}catch(error){toast('导入失败：'+error.message);}});
  render();if(!state)newGame();else showPhase();
  if(document.modelContext?.registerTool){
    const lifecycle=new AbortController(),definitions=[{name:'read_xiuxian_life',description:'读取修士的随机灵根、资质、真实年月、寿元、职务、行囊及可进行行动，不改变进度。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>state?{name:state.name,root:state.root,rootStatus:E.rootStatus(state),rootElements:[...state.rootElements],path:state.path,pathStatus:E.pathStatus(state),time:E.timeStatus(state),lifespan:E.lifespanStatus(state),sect:E.sectStatus(state),morality:E.moralityStatus(state),world:E.worldStatus(state),companions:D.companions.map(c=>({id:c.id,...E.companionStatus(state,c.id)})),dungeons:E.dungeonStatus(state),auction:E.auctionStatus(state),phase:state.phase,realm:E.realmInfo(state).name,health:state.health,resolve:state.resolve,stones:state.stones,cultivation:state.cultivation,inventory:{...state.inventory},actions:D.actions.filter(a=>!a.requirePath||a.requirePath===state.path).map(a=>({id:a.id,name:a.name,time:E.actionTime(state,a.id),effects:E.actionPreview(state,a.id),error:E.actionError(state,a.id)}))}:{started:false}},{name:'perform_cultivation_action',description:'立即进行一项修仙行动，按该行动标注耗时推进真实月份并结算收益；可能引出需要玩家决定的随机事件。',inputSchema:{type:'object',properties:{actionId:{type:'string'}},required:['actionId'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!state)throw Error('请先创建修士');if(!input||typeof input.actionId!=='string')throw Error('请提供一个行动 ID');const result=E.performAction(state,input.actionId);save();render();showActionReceipt(result);return {result,time:E.timeStatus(state),phase:state.phase,executed:true};}}];
    for(const definition of definitions){try{Promise.resolve(document.modelContext.registerTool(definition,{signal:lifecycle.signal})).catch(()=>{});}catch(_){}}
    window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
  }
})();
