(function () {
  'use strict';
  const D = X_DATA, E = X_ENGINE, KEY = 'XIAN-ZHI-DIAN-v1';
  const $ = s => document.querySelector(s);
  const esc = v => String(v == null ? '' : v).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const num = n => Number(n || 0).toLocaleString('zh-CN');
  const glyphs = {
    mountain:'m2 19 7-13 5 9 3-5 5 9H2m4-7 3 2 3-2',
    sword:'m14 3 7-1-1 7-11 11-5-5zM3 21l4-4m-4-3 7 7',
    book:'M3 4h6a3 3 0 0 1 3 3v14a4 4 0 0 0-4-2H3zm18 0h-6a3 3 0 0 0-3 3m9-3v15h-5a4 4 0 0 0-4 2',
    leaf:'M20 3C9 2 2 7 4 15s14 7 16-12zM4 20 16 8m-7 7v-5m3 2h5',
    flame:'M13 2c1 7-6 8-3 12 1-2 3-3 5-4 0 5 5 5 3 10-3 5-13 3-13-3 0-5 6-6 8-15z',
    sun:'M12 2v2m0 16v2M2 12h2m16 0h2M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2M17 12a5 5 0 1 1-10 0 5 5 0 0 1 10 0',
    moon:'M20 15A9 9 0 0 1 9 4a9 9 0 1 0 11 11z',
    gem:'m3 8 4-5h10l4 5-9 13L3 8zm0 0h18M8 8l4 13 4-13m-9-5 1 5 4-5 4 5 1-5',
    bag:'M8 3h8l-2 5 6 10a3 3 0 0 1-3 4H7a3 3 0 0 1-3-4l6-10-2-5zm2 5h4m-6 6h8',
    flask:'M9 2h6m-5 0v8l-6 9a2 2 0 0 0 2 3h12a2 2 0 0 0 2-3l-6-9V2M7 16h10',
    scroll:'M7 3h12v14H7a3 3 0 0 1-3-3V6a3 3 0 0 1 3-3zm0 0v11M7 17v3h14v-3M10 7h6m-6 4h6',
    shield:'m12 2 9 4v6c0 6-9 10-9 10S3 18 3 12V6zm-5 10 3 3 7-7',
    heart:'M20 5c-3-3-6 0-8 2-2-2-5-5-8-2s0 7 8 14c8-7 11-11 8-14z',
    compass:'M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0m-6-4-3 6-5 2 2-5z',
    temple:'m2 9 10-7 10 7M4 9h16M6 9v11m6-11v11m6-11v11M3 22h18',
    users:'M16 21v-3a4 4 0 0 0-4-4H7a4 4 0 0 0-4 4v3m17 0v-3a4 4 0 0 0-3-4M12 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0m4-3a3 3 0 0 1 0 6',
    paw:'M7 14c-1-5 4-8 6-5 2 2 1 3 4 5 5 6-1 8-5 6-6 2-10-1-5-6zM4 6v3m5-6v3m6-3v3m5 0v3',
    arrow:'M3 12h18m-6-6 6 6-6 6', plus:'M12 5v14M5 12h14', close:'m6 6 12 12M6 18 18 6',
    help:'M9 8a3 3 0 1 1 5 2c-2 1-2 2-2 3m0 4h.01M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',
    save:'M5 3h12l4 4v14H3V3zm2 0v6h10V3M7 21v-7h10v7',
    refresh:'M20 7a8 8 0 1 0 0 10m0-14v5h-5', star:'m12 2 3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1z',
    hammer:'m3 21 10-10m-3-5 5-4 7 7-4 5z', cloud:'M6 18a5 5 0 1 1 0-10 7 7 0 0 1 13 3 4 4 0 0 1 0 8H6'
  };
  const icon = name => /^[\u4e00-\u9fff◉]$/.test(name || '') ? `<span class="han-icon" aria-hidden="true">${esc(name)}</span>` : `<svg class="icon" aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="${glyphs[name] || glyphs.star}"/></svg>`;
  const landscape = `<svg class="landscape" viewBox="0 0 1000 160" preserveAspectRatio="xMidYMax slice" aria-hidden="true"><circle cx="770" cy="54" r="28" fill="currentColor" opacity=".11"/><path d="m280 160 160-123 78 68 101-82 130 107 92-49 159 79z" fill="currentColor" opacity=".05"/><path d="m110 160 115-65 60 31 115-86 97 98 73-45 77 67zm405 0 126-94 82 81 69-36 90 49z" fill="currentColor" opacity=".08"/><path d="m0 160 176-41 97 29 104-18 126 30zm653 0 137-33 103 20 107-16v29z" fill="currentColor" opacity=".10"/></svg>`;
  let state = null, filter = '修行', draft = null, toastTimer, shopTab = 'goods', receipt = null, loadError = '', saveOK = true;
  try {
    const raw = localStorage.getItem(KEY);
    if (raw) { const saved = JSON.parse(raw); if (saved.format !== 'XIUXIAN-LIFE') throw Error('存档格式不符'); state = E.validate(saved.state); }
  } catch (_) { loadError = '原存档暂时无法读取。可从存档管理导入备份，或重新启程。'; }
  $('#modal-root').innerHTML = '<dialog id="game-dialog" aria-labelledby="dialog-title"></dialog><input id="import-file" type="file" accept="application/json,.json" hidden>';
  const dialog = $('#game-dialog');
  function toast(text) { clearTimeout(toastTimer); $('#toast').textContent = text; $('#toast').classList.add('visible'); toastTimer = setTimeout(() => $('#toast').classList.remove('visible'), 3500); }
  function save() { if (!state) return; try { localStorage.setItem(KEY, JSON.stringify({format:'XIUXIAN-LIFE',savedAt:new Date().toISOString(),state})); saveOK = true; } catch (_) { saveOK = false; toast('浏览器暂时无法保存，请从存档管理导出备份。'); } }
  function modal(html, wide = false) { dialog.className = wide ? 'wide-dialog' : ''; dialog.innerHTML = html; if (!dialog.open) dialog.showModal(); dialog.scrollTop = 0; $('#dialog-title')?.focus({preventScroll:true}); }
  function close() { dialog.close(); }
  function top(kicker) { return `<div class="dialog-top"><span class="eyebrow">${esc(kicker)}</span><button class="icon-button" data-command="close" aria-label="关闭弹窗">${icon('close')}</button></div>`; }
  function heading(title, sub = '') { return `<h2 id="dialog-title" tabindex="-1">${esc(title)}</h2>${sub ? `<p class="dialog-lead">${esc(sub)}</p>` : ''}`; }
  function chips(effects) { return `<div class="effect-chips">${Object.entries(effects || {}).filter(([,v]) => v !== 0).map(([k,v]) => `<span class="effect-chip ${v < 0 ? 'loss' : 'gain'}">${esc(E.effectsText({[k]:v}))}</span>`).join('')}</div>`; }
  function notes(lines, className = '') { return lines?.length ? `<ul class="notes ${className}">${lines.map(t => `<li>${esc(t)}</li>`).join('')}</ul>` : ''; }
  function progress(label, value, max, color = '') { const safe = Math.min(max, Math.max(0, value)); return `<div class="meter-label"><span>${esc(label)}</span><b>${num(value)} <small>/ ${num(max)}</small></b></div><div class="meter ${color}" role="meter" aria-label="${esc(label)}" aria-valuemin="0" aria-valuemax="${max}" aria-valuenow="${safe}"><i style="width:${Math.min(100, safe / max * 100)}%"></i></div>`; }
  const find = (list,id) => list.find(x => x.id === id);
  function header() { return `<header class="site-header"><a class="brand" href="./" aria-label="仙之巅首页"><span class="brand-seal">仙</span><span>仙之巅<small>一念入山海 · 百转问长生</small></span></a><nav aria-label="游戏工具"><button class="text-button" data-command="help">${icon('help')}<span>修行手札</span></button><button class="text-button" data-command="saves">${icon('save')}<span>存档管理</span></button><button class="text-button" data-command="new">${icon('refresh')}<span>重入轮回</span></button></nav></header>`; }
  function character() {
    const root = find(D.roots,state.root), path = find(D.paths,state.path), sect = find(D.sects,state.sect);
    return `<section class="panel character-panel"><div class="character-top"><span class="portrait" aria-hidden="true">${esc(state.name.slice(0,1))}</span><div><span class="eyebrow">山海间的一位修士</span><h1>${esc(state.name)}</h1><p>${esc(root?.name)} · ${esc(path?.name)}</p></div></div><div class="character-time"><div><b>${state.age}</b><span>岁 · 春秋</span></div><div><b>${state.year}<small> / 60</small></b><span>修行之年</span></div></div><div class="body-stats">${progress('气血',state.health,100,state.health<25?'red':'')}${progress('心境',state.resolve,100,'gold')}</div><div class="ability-list"><div><span>悟性 <small>参悟与破境</small></span><b>${state.insight}</b></div><div><span>体魄 <small>战力与险境</small></span><b>${state.physique}</b></div><div><span>神识 <small>战力与识物</small></span><b>${state.spirit}</b></div><div><span>声望 <small>机缘与战力</small></span><b>${state.reputation}</b></div></div><div class="power-line"><span>${icon('sword')} 综合战力</span><b>${num(E.power(state))}</b></div><details class="small-details"><summary>战力与破境如何成长</summary><p>境界、体魄、神识和声望共同构成战力，装备、符箓与长期机缘也会加成。悟性与心境越高，突破境界的成功率越高。</p><p>每年恢复气血与心境各 5 点；气血归零会结束此生。</p></details><div class="talent-tags">${state.talents.map(id => { const t=find(D.talents,id); return `<span title="${esc(t?.desc)}" class="${t?.rarity==='rare'?'rare':''}">${esc(t?.name)}</span>`; }).join('')}</div><div class="sect-line"><span>${icon('temple')}${esc(sect?.name || '尚未拜入山门')}</span><button class="link-button" data-command="sects">${sect?'详情':'拜访'} ${icon('arrow')}</button></div>${sect?`<div class="contribution">山门贡献 <b>${num(state.contribution)}</b></div>`:''}</section>`;
  }
  function bagPanel() {
    const items = D.items.filter(i => state.inventory[i.id] > 0), buffs = D.buffs.filter(b => state.buffs[b.id] > 0), conditions = D.conditions.filter(c => state.conditions.includes(c.id));
    return `<section class="panel bag-panel"><div class="section-top"><h2>${icon('bag')} 行囊</h2><button class="link-button" data-command="bag">打开 ${icon('arrow')}</button></div><div class="wallet"><div><span>灵石</span><b>${num(state.stones)}</b></div><button class="outline-button" data-command="shop">逛坊市 ${icon('arrow')}</button></div>${items.length?`<div class="bag-chips">${items.map(i=>`<button data-command="bag">${esc(i.name)} <b>×${state.inventory[i.id]}</b></button>`).join('')}</div>`:'<p class="muted small">一本心法、一柄灵剑，也许就是下一次破境的契机。</p>'}${buffs.map(b=>`<div class="status-note"><b>${esc(b.name)} · 剩余 ${state.buffs[b.id]} 年</b><p>${esc(b.desc)}</p></div>`).join('')}${conditions.map(c=>`<div class="status-note warning"><b>${esc(c.name)}</b><p>${esc(c.desc)}</p><button class="link-button" data-jump="rest">安排调养 ${icon('arrow')}</button></div>`).join('')}</section>`;
  }
  function realmPanel() {
    const realm=E.realmInfo(state), status=E.breakthroughStatus(state), next=D.realms[state.realm+1];
    return `<section class="panel realm-panel">${landscape}<div class="realm-intro"><div><span class="eyebrow">此刻的道途</span><h2>${esc(realm.name)}<span>${esc(realm.subtitle)}</span></h2></div><span class="realm-mark" aria-hidden="true">${state.realm===5?'圆满':'问道'}</span></div><ol class="realm-road" aria-label="修仙境界">${D.realms.map((r,i)=>`<li class="${i===state.realm?'current':i<state.realm?'passed':''}" ${i===state.realm?'aria-current="step"':''}><span>${String(i+1).padStart(2,'0')}</span>${esc(r.name)}</li>`).join('')}</ol>${next?`<div class="cultivation-row"><div class="cultivation-progress">${progress('修为积累',state.cultivation,status.threshold)}<p>${status.ready?`破境条件已具备 · 当前成功率 ${Math.round(status.chance*100)}%`:esc(status.reason)}<span>下一境 · ${esc(next.name)}</span></p></div><button class="primary-button breakthrough-button" data-action="breakthrough" ${E.actionError(state,'breakthrough')?'disabled':''}>尝试突破 ${icon('arrow')}</button></div>`:'<p class="ascended-note">越过山海尽头，这一段道途已圆满。</p>'}</section>`;
  }
  function planPanel() {
    const active=state.phase==='planning';
    return `<section class="panel plan-panel"><div class="section-top"><div><span class="eyebrow">第 ${String(state.year).padStart(2,'0')} 年 · 安排修行</span><h2>这一年，心向何处？</h2></div><span class="phase-pill">${{planning:'待落子',event:'机缘待决',ending:'此生留卷'}[state.phase]}</span></div><div class="plan-slots">${[0,1,2].map(i=>{const a=find(D.actions,state.plan[i]);return a?`<button class="plan-slot filled" data-remove="${i}" ${active?'':'disabled'} aria-label="取消第 ${i+1} 项 ${esc(a.name)}"><span class="slot-num">${['壹','贰','叁'][i]}</span><span>${icon(a.icon)}<b>${esc(a.name)}</b></span>${icon('close')}</button>`:`<div class="plan-slot empty"><span class="slot-num">${['壹','贰','叁'][i]}</span><span>从下方选一件事</span>${icon('plus')}</div>`;}).join('')}</div><div class="plan-bottom"><p>${active?'行动依次结算，可重复安排。点击已选行动可取消。':state.phase==='event'?'年末机缘尚未作答，先看看山海送来了什么。':'此生的每一笔，都已落在仙途纪事中。'}</p><button class="primary-button" data-command="advance" ${active&&state.plan.length!==3?'disabled':''}>${active?`度过这一年 <span>${state.plan.length} / 3</span>`:state.phase==='event'?'处理年末机缘':'展开此生结局'} ${icon('arrow')}</button></div></section>`;
  }
  function actionExtra(a) { const parts=[]; for(const [id,n] of Object.entries(a.costItems||{}))parts.push(`消耗${find(D.items,id)?.name||id} ×${n}`);for(const [id,n] of Object.entries(a.gainItems||{}))parts.push(`获得${find(D.items,id)?.name||id} ×${n}`);if(a.clearCondition)parts.push(`解除${find(D.conditions,a.clearCondition)?.name||a.clearCondition}`);return parts; }
  function actionPanel() {
    const categories=['修行','山门','游历','生活'];
    return `<section class="action-section" id="action-section"><div class="action-heading"><h2>修行诸事</h2><div class="filters" aria-label="行动分类">${categories.map(c=>`<button data-filter="${c}" class="${filter===c?'selected':''}" aria-pressed="${filter===c}">${c}</button>`).join('')}</div></div><div class="action-grid">${D.actions.filter(a=>a.category===filter).map(a=>{const error=E.actionError(state,a.id),effects=a.id==='breakthrough'?{}:E.actionPreview(state,a.id),extra=actionExtra(a);return `<article class="action-card ${error?'unavailable':''}"><div class="action-title"><span class="action-symbol">${icon(a.icon)}</span><h3>${esc(a.name)}</h3><button class="add-action" data-action="${esc(a.id)}" ${error?'disabled':''} aria-label="安排${esc(a.name)}">${icon('plus')}</button></div><p>${esc(a.desc)}</p>${a.id==='breakthrough'?`<div class="action-outcome">当前成功率 ${Math.round(E.breakthroughStatus(state).chance*100)}% · 占 1 次行动</div>`:chips(effects)}${extra.length?`<div class="action-outcome">${extra.map(esc).join(' · ')}</div>`:''}<div class="action-foot ${error?'locked':''}">${esc(error || a.hint || '可安排 · 占 1 次行动')}</div></article>`;}).join('')}</div></section>`;
  }
  function storyRecords(all=false) {
    const stories=D.stories.map(s=>E.storyStatus(state,s.id)).filter(s=>s&&(all||s.status!=='active'));
    return stories.length?`<details class="story-history" ${all?'open':''}><summary>已走过的机缘 · ${stories.length} 段</summary>${stories.map(s=>`<div class="history-story"><div><b>${esc(s.name)}</b><span>${{active:'未完',completed:'圆满',abandoned:'放下'}[s.status]}</span></div><p>${esc(s.ending || `已完成 ${s.progress} / ${s.target} 次${s.actionName}`)}</p></div>`).join('')}</details>`:'';
  }
  function perksHTML() { return state.perks.length?`<div class="perks-list">${state.perks.map(id=>{const p=find(D.perks,id);return `<div><span class="tiny-seal">缘</span><p><b>${esc(p?.name)}</b><span>${esc(p?.desc)}</span></p></div>`;}).join('')}</div>`:''; }
  function storiesPanel() {
    const active=D.stories.map(s=>E.storyStatus(state,s.id)).filter(s=>s?.status==='active');
    return `<section class="panel stories-panel"><div class="section-top"><h2>${icon('scroll')} 尘缘未了</h2><span class="muted small">相逢，自有后文</span></div>${active.length?`<div class="story-grid">${active.map(s=>`<article class="story-card"><div class="story-top"><h3>${esc(s.name)}</h3><span>${s.ready?'等待后续':`余 ${s.remainingYears} 年`}</span></div><p>${esc(s.desc)}</p>${progress(s.actionName,s.progress,s.target,'gold')}<p class="story-reward">圆满所得：${esc(s.rewardDesc)}</p><button class="link-button" data-jump="${esc(find(D.stories,s.id).actionId)}" ${s.ready||state.phase!=='planning'?'disabled':''}>前往安排 ${icon('arrow')}</button></article>`).join('')}</div>`:'<div class="empty-stories"><span class="empty-orbit" aria-hidden="true">缘</span><p>山海未远，相逢有时。<span>游历中可能遇见护送委托、残卷秘闻与灵兽羁绊。接下后，需要用行动兑现。</span></p></div>'}${perksHTML()}${storyRecords()}</section>`;
  }
  function recentPanel() {
    return `<section class="panel chronicle-panel"><div class="section-top"><h2>${icon('book')} 仙途纪事</h2><span class="muted small">${state.log.length} 笔留痕</span></div>${state.lastYear?`<div class="last-growth"><div><b>第 ${state.lastYear.year} 年 · 修行所得</b><span>行动结算，机缘另记</span></div>${chips(state.lastYear.effects)}${notes(state.lastYear.notes)}</div>`:''}${state.lastEvent?`<div class="last-encounter"><span class="tiny-seal">遇</span><div><b>${esc(state.lastEvent.title)}</b><p>${esc(state.lastEvent.result)}</p>${chips(state.lastEvent.effects)}${notes(state.lastEvent.changes)}</div></div>`:''}<details class="chronicle" ${state.log.length<5?'open':''}><summary>翻阅修行年表</summary>${state.log.length?`<ol>${state.log.map(l=>`<li><span>第 ${l.year} 年</span><p>${esc(l.text)}</p></li>`).join('')}</ol>`:'<p class="muted small">第一行，留待你落笔。</p>'}</details></section>`;
  }
  function render() {
    if(!state){$('#app').innerHTML=`<div class="app-shell">${header()}<main class="empty-start">${landscape}<span class="intro-seal">山海问道</span><p class="eyebrow">文字修仙 · 六十载道途</p><h1>山中无日月，<br>此生有回响。</h1><p>择灵根，修心境。踏过人间烟火，问一问长生。</p><button class="primary-button" data-command="new">开启一段仙途 ${icon('arrow')}</button>${loadError?`<p class="load-error">${esc(loadError)}</p>`:''}</main>${footer()}</div>`;return;}
    $('#app').innerHTML=`<div class="app-shell">${header()}<div class="page-caption"><span>山海历 · 第 ${state.year} 年</span><span>${state.phase==='ending'?'此生已成卷':saveOK?'落子无悔，进度已自动留存':'请导出存档以保存进度'}</span></div><main class="game-layout"><aside class="sidebar">${character()}${bagPanel()}</aside><div class="main-column">${realmPanel()}${planPanel()}${state.phase!=='ending'?actionPanel():`<section class="panel ending-callout"><span class="intro-seal">此生</span><div><h2>${esc(state.ending?.title || '仙途成卷')}</h2><p>${esc(state.ending?.desc)}</p></div><button class="outline-button" data-command="ending">展开仙途长卷 ${icon('arrow')}</button></section>`}${storiesPanel()}${recentPanel()}</div></main>${footer()}</div>`;
  }
  function footer(){return '<footer class="site-footer"><span>仙之巅 <i>·</i> 山海间，写自己的道</span><span>XIAN ZHI DIAN · v1.0.0</span></footer>';}
  function randomSeed(){try{return crypto.getRandomValues(new Uint32Array(1))[0]||1;}catch(_){return (Date.now() ^ Math.floor(Math.random()*0xffffffff))>>>0||1;}}
  function newGame() { const seed=randomSeed();draft={name:'无名',root:D.roots[0].id,path:D.paths[0].id,talents:[],seed,pool:E.drawTalents(seed,8),rerolls:2};showNew(); }
  function draftEffects(entry){const parts=[];if(Object.keys(entry.start||{}).length)parts.push(E.effectsText(entry.start));for(const [id,effects] of Object.entries(entry.actions||{}))parts.push(`${find(D.actions,id)?.name||id}：${E.effectsText(effects)}`);if(entry.breakthroughBonus)parts.push(`破境成功率 +${Math.round(entry.breakthroughBonus*100)}%`);return parts.join('；');}
  function showNew(){
    modal(`${top('卷首 · 一念起仙途')}${heading('天地之间，你是何人？','灵根是来处，天赋是际遇。往后的六十年，由你落子。')}${state?'<div class="notice">开始新仙途将替换当前进度。想留住这一世，可先关闭弹窗，到「存档管理」导出备份。</div>':''}${loadError?`<div class="notice">${esc(loadError)}</div>`:''}<div class="new-name"><label for="character-name">道号</label><input id="character-name" maxlength="16" value="${esc(draft.name)}" placeholder="给自己取个道号" autocomplete="off"><span>最多 16 字</span></div><section class="creation-section"><div class="creation-title"><h3><span>壹</span> 天生灵根</h3><span>选择一系，随身修行</span></div><div class="root-grid">${D.roots.map((r,i)=>`<button class="root-choice ${draft.root===r.id?'selected':''}" data-root="${esc(r.id)}" aria-pressed="${draft.root===r.id}"><span class="root-element root-${i}">${esc(r.name.slice(0,1))}</span><strong>${esc(r.name)}</strong><p>${esc(r.desc)}</p><small>${esc(draftEffects(r))}</small></button>`).join('')}</div></section><section class="creation-section"><div class="creation-title"><h3><span>贰</span> 心之所向</h3><span>选择最初的修行方向</span></div><div class="path-grid">${D.paths.map((p,i)=>`<button class="path-choice ${draft.path===p.id?'selected':''}" data-path="${esc(p.id)}" aria-pressed="${draft.path===p.id}">${icon(['sword','flask','compass'][i])}<div><strong>${esc(p.name)}</strong><p>${esc(p.desc)}</p><small>${esc(draftEffects(p))}</small></div></button>`).join('')}</div></section><section class="creation-section"><div class="creation-title"><h3><span>叁</span> 命中天赋 <small>已选 ${draft.talents.length} / 2</small></h3><button class="link-button" data-command="reroll" ${draft.rerolls?'':'disabled'}>${icon('refresh')} 重抽 · 余 ${draft.rerolls} 次</button></div><div class="talent-grid">${draft.pool.map(id=>{const t=find(D.talents,id);return `<button class="talent-choice ${draft.talents.includes(id)?'selected':''} ${t.rarity==='rare'?'rare':''}" data-talent="${esc(id)}" aria-pressed="${draft.talents.includes(id)}"><div><strong>${esc(t.name)}</strong><span>${t.rarity==='rare'?'稀有':'天赋'}</span></div><p>${esc(t.desc)}</p><small>${esc(draftEffects(t))}</small></button>`;}).join('')}</div></section><div class="creation-bottom"><p>从 ${D.talents.length} 种天赋中抽取 8 种，选择 2 种。<br>此处没有唯一正解，来日还会有新的机缘。</p><button class="primary-button" data-command="start" ${draft.talents.length!==2?'disabled':''}>开始这段仙途 ${icon('arrow')}</button></div>`,true);
  }
  function showYear(){const report=state.lastYear;if(!report){showPhase();return;}modal(`${top(`第 ${report.year} 年 · 岁末留痕`)}${heading('又一载山中岁月。','每次修行都有积累。看看这一年的收获，再赴下一场机缘。')}<div class="report-effects">${chips(report.effects)}</div>${notes(report.notes,'report-notes')}<div class="report-summary"><span>当前境界</span><strong>${esc(E.realmInfo(state).name)}</strong><span>现有灵石</span><strong>${num(state.stones)}</strong></div><button class="primary-button full-width" data-command="continue-report">${state.phase==='ending'?'展开此生长卷':'看看年末机缘'} ${icon('arrow')}</button>`);}
  function consequences(choice){return notes(E.consequencesText(state,choice),'choice-consequences');}
  function showEvent(){const event=find(D.events,state.pendingEvent);if(!event)return;modal(`${top(`第 ${state.year} 年 · 山海机缘`)}<div class="event-emblem">${icon(event.icon || 'compass')}</div>${heading(event.title,event.body)}<div class="event-choices">${event.choices.map((c,i)=>{const error=E.choiceError(state,c);return `<div class="event-choice ${error?'choice-locked':''}"><button data-choice="${i}" ${error?'disabled':''}><span class="choice-index">${['甲','乙','丙','丁'][i]||i+1}</span><b>${esc(c.text)}</b>${icon('arrow')}</button>${chips(c.effects)}${consequences(c)}${c.check?`<div class="check-preview"><span>以${esc(c.check.stat==='power'?'战力':E.labels[c.check.stat]||c.check.stat)}应对 · 当前成功率 <b>${Math.round(E.checkChance(state,c.check)*100)}%</b></span><details><summary>查看两种可能</summary><div><b>若成功</b><p>${esc(c.check.success.result)}</p>${chips(c.check.success.effects)}${consequences(c.check.success)}</div><div><b>若未成</b><p>${esc(c.check.failure.result)}</p>${chips(c.check.failure.effects)}${consequences(c.check.failure)}</div></details></div>`:''}${error?`<p class="choice-error">${esc(error)}</p>`:''}</div>`;}).join('')}</div>`);}
  function showResult(){const r=state.lastEvent;if(!r){showPhase();return;}modal(`${top('机缘落定 · 所行皆有回响')}<div class="result-seal">${r.outcome==='success'?'成':r.outcome==='failure'?'悟':'缘'}</div>${heading(r.title,r.result)}${chips(r.effects)}${notes(r.changes,'report-notes')}<button class="primary-button full-width" data-command="next">${state.phase==='ending'?'查看此生结局':`迈入第 ${state.year} 年`} ${icon('arrow')}</button>`);}
  function showPhase(){if(state?.phase==='event')showEvent();else if(state?.phase==='ending')showEnding();}
  function showEnding(){if(!state?.ending)return;const end=state.ending;modal(`${top('终卷 · 山海记得来路')}<div class="ending-symbol">${icon(end.id==='ascended'?'sun':'mountain')}</div>${heading(end.title,`${state.name}，${end.desc}`)}<div class="ending-grid"><div><b>${esc(E.realmInfo(state).name)}</b><span>此生境界</span></div><div><b>${state.age}</b><span>岁月春秋</span></div><div><b>${state.breakthroughs}</b><span>成功破境</span></div><div><b>${num(E.power(state))}</b><span>最终战力</span></div></div><div class="ending-note">万种道途，未必都要通向同一个终点。你所相逢的人与事，已经成为这一生。</div>${storyRecords(true)}${perksHTML()}<div class="dialog-bottom"><button class="outline-button" data-command="export">留存此生</button><button class="primary-button" data-command="new">重入轮回 ${icon('refresh')}</button></div>`,true);}
  function itemDetails(item){const lines=[];for(const [id,effects] of Object.entries(item.actions||{}))lines.push(`${find(D.actions,id)?.name||id}额外：${E.effectsText(effects)}`);if(item.powerBonus)lines.push(`持有时战力 +${item.powerBonus}`);if(item.useEffects)lines.push(`使用后：${E.effectsText(item.useEffects)}`);if(item.buff){const b=find(D.buffs,item.buff);if(b)lines.push(`${b.name} · 持续 ${b.duration} 年：${b.desc}`);}if(item.clearCondition)lines.push(`解除${find(D.conditions,item.clearCondition)?.name||item.clearCondition}`);for(const a of D.actions.filter(a=>a.requireItem===item.id))lines.push(`持有后解锁「${a.name}」`);return notes(lines,'item-details');}
  function showShop(){
    const owned=D.items.filter(i=>state.inventory[i.id]>0),list=shopTab==='goods'?D.items:owned;
    modal(`${top('坊市 · 灵物有价，机缘无价')}${heading(shopTab==='goods'?'山脚有一座小坊市。':'把机缘，收入行囊。','装备持有即生效；丹药与符箓在背包中使用。买卖与使用不占年度行动。')}<div class="shop-toolbar"><div class="shop-tabs"><button data-shop-tab="goods" class="${shopTab==='goods'?'selected':''}">坊市灵物</button><button data-shop-tab="bag" class="${shopTab==='bag'?'selected':''}">我的行囊 <span>${owned.length}</span></button></div><div class="shop-balance">${icon('gem')}<span>灵石</span><b>${num(state.stones)}</b></div></div>${receipt?`<section class="receipt" role="status"><b>${esc(receipt.title)}</b><p>${esc(receipt.text)}</p>${chips(receipt.effects)}${notes(receipt.changes)}</section>`:''}${!list.length?'<div class="empty-bag"><span class="empty-orbit">囊</span><p>行囊尚空。可去坊市添置灵物，或安排采药、采矿。</p></div>':`<div class="shop-grid">${list.map(item=>{const status=E.itemStatus(state,item.id);return `<article class="shop-item"><div class="shop-item-top"><span class="item-icon">${icon(item.icon)}</span><div><h3>${esc(item.name)}</h3><span>${item.kind==='equipment'?'随身装备':item.useEffects||item.buff||item.clearCondition?'消耗灵物':'炼制材料'} · 持有 ${status.owned} / ${item.max}</span></div>${shopTab==='goods'?`<b>${num(status.price)}<small>灵石</small></b>`:''}</div><p>${esc(item.desc)}</p>${itemDetails(item)}<div class="shop-item-bottom">${shopTab==='goods'?`<button class="outline-button" data-buy="${esc(item.id)}" ${status.canBuy?'':'disabled'}>购入一件 ${icon('plus')}</button>${!status.canBuy?`<span>${esc(status.buyReason)}</span>`:''}`:`<button class="outline-button" data-use="${esc(item.id)}" ${status.canUse?'':'disabled'}>${item.kind==='equipment'?'已随身生效':'使用一件'}</button><span>${esc(status.canUse?'使用后立即生效':status.useReason)}</span>`}</div></article>`;}).join('')}</div>`}<p class="shop-footnote">灵石仅为游戏内资源。计划所需灵石与材料会优先保留；相同持续效果生效时不可重复使用。</p>`,true);
  }
  function openShop(tab='goods'){if(!state){toast('先开启一段仙途，再去坊市走走。');return;}shopTab=tab;receipt=null;showShop();}
  function showSects(){if(!state)return;const current=find(D.sects,state.sect);modal(`${top('山门 · 在江湖中寻一处归所')}${heading(current?`${current.name}，便是此间归处。`:'山门三千，择一而入。','筑基后可拜入一座山门。拜师不耗行动，需先清空计划；本局选定后不再更换。')}<div class="sect-grid">${D.sects.map((sect,i)=>{const error=E.sectError(state,sect.id),selected=state.sect===sect.id,benefits=[];for(const [id,effects] of Object.entries(sect.actions||{}))benefits.push(`${find(D.actions,id)?.name||id}额外：${E.effectsText(effects)}`);if(sect.breakthroughBonus)benefits.push(`破境成功率 +${Math.round(sect.breakthroughBonus*100)}%`);if(sect.shopDiscount)benefits.push(`坊市价格优惠 ${Math.round(sect.shopDiscount*100)}%`);return `<article class="sect-card ${selected?'selected':''}"><span class="sect-number">${['壹','贰','叁'][i]}</span><h3>${esc(sect.name)}</h3><p>${esc(sect.desc)}</p>${notes(benefits)}<button class="outline-button" data-sect="${esc(sect.id)}" ${error?'disabled':''}>${selected?'已入此门':'拜入此门'}</button>${error?`<p class="small muted">${esc(error)}</p>`:''}</article>`;}).join('')}</div><div class="notice">入门后开启山门任务，积攒灵石与贡献。门派加成可在对应行动的预计收获中直接看到。</div>`,true);}
  function help(){modal(`${top('修行手札 · 初入山海')}${heading('慢慢修，也是一条道。')}<div class="help-grid"><section><span>01</span><h3>落子之前，认一认自己</h3><p>选择灵根与修行方向，从 ${D.talents.length} 项天赋中抽 8 选 2，可重抽 2 次。灵根、方向和天赋会改变初始属性或行动收益，开局不决定终局。</p></section><section><span>02</span><h3>一年三事，有舍有得</h3><p>每年安排 3 次行动，按顺序结算；普通行动可重复。采药、采矿可获得材料，炼丹与制符会消耗材料和灵石。每年结束恢复气血与心境各 5 点，再遇见一次随机机缘。</p></section><section><span>03</span><h3>修为满了，还要叩一叩天门</h3><p>积累足够修为，且气血、心境均至少 20，才能安排一次突破。悟性、心境、山门、天赋和丹药影响成功率；突破占 1 次行动，每年最多一次。失败会失去门槛修为的 20%、10 气血与 8 心境。成功后迈入下一境；从化神再突破，即可飞升。</p></section><section><span>04</span><h3>战力与属性，各有用处</h3><p>境界、体魄、神识、声望与装备共同构成战力。事件会受境界、年份和属性影响，冒险选项会显示当前成功率与两种结果。气血归零会结束此生；心境影响破境，可通过调养恢复。</p></section><section><span>05</span><h3>灵石换灵物，材料炼仙丹</h3><p>坊市可购买心法、灵剑、丹药与符箓。装备持有即生效，消耗灵物在行囊中使用，不占行动。持续效果按完整修行年计算，年末机缘结束后扣除时长；已安排的材料和灵石会保留。伤势可通过调养或对应丹药解除。</p></section><section><span>06</span><h3>山门与机缘，会留下后文</h3><p>筑基后可以拜师，先清空年度计划再选择。遇见连续故事后，面板会显示任务、进度、截止时间和报酬；目标达成或期限到来，就会迎来后续。灵兽、传承与故交会留下长期加成，并记录在此生长卷中。</p></section><section><span>07</span><h3>六十年里，走自己的路</h3><p>从 16 岁起，共有 60 个修行年；飞升、气血耗尽或最后一年结束时生成结局。行囊、故事记录与长久机缘会留下。没有必须照抄的最优人生。</p></section><section><span>08</span><h3>给这段仙途留一份底稿</h3><p>游戏自动保存在当前浏览器，不上传进度。换设备或清理浏览器前，请先导出存档。导入备份会先检查格式，再由你确认替换。</p></section></div><div class="notice">这是一个虚构的修仙文字世界。所有灵石、丹药与命运，均属于游戏。</div><button class="primary-button" data-command="close">收起手札，继续修行 ${icon('arrow')}</button>`,true);}
  function saves(){modal(`${top('留卷 · 让这段仙途有迹可寻')}${heading('山河很远，先留个备份。','进度仅保存在当前浏览器。导出后，可在另一台设备导入继续修行。')}${state?`<div class="save-summary"><span class="portrait small-portrait">${esc(state.name.slice(0,1))}</span><div><b>${esc(state.name)}</b><p>${esc(E.realmInfo(state).name)} · 第 ${state.year} 年 · ${state.age} 岁</p></div></div>`:'<p class="notice">尚未开启新仙途，可以在这里导入之前的备份。</p>'}<div class="dialog-bottom"><button class="outline-button" data-command="import">导入存档</button><button class="primary-button" data-command="export" ${state?'':'disabled'}>导出当前仙途 ${icon('save')}</button></div>`);}
  function exportSave(){if(!state)return;const blob=new Blob([JSON.stringify({format:'XIUXIAN-LIFE',savedAt:new Date().toISOString(),state},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`xian-zhi-dian-year-${state.year}.json`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('仙途已导出，请妥善保管。');}
  function mutate(fn){try{fn();save();render();return true;}catch(error){toast(error.message||'这一步暂时无法完成。');return false;}}
  function jump(id){const action=find(D.actions,id);if(!action)return;filter=action.category;close();render();$('#action-section')?.scrollIntoView({behavior:'smooth',block:'start'});document.querySelector(`[data-action="${CSS.escape(id)}"]`)?.focus({preventScroll:true});}
  const commands={close,new:newGame,help,saves,shop:()=>openShop(),bag:()=>openShop('bag'),sects:showSects,ending:showEnding,export:exportSave,import:()=>$('#import-file').click(),advance:()=>{if(!state)return;if(state.phase==='planning'){if(mutate(()=>E.advance(state)))showYear();}else showPhase();},'continue-report':()=>{close();showPhase();},next:()=>{close();if(state.phase==='ending')showEnding();},reroll:()=>{if(!draft?.rerolls)return;draft.seed=randomSeed();draft.pool=E.drawTalents(draft.seed,8);draft.talents=[];draft.rerolls--;const scroll=dialog.scrollTop;showNew();dialog.scrollTop=scroll;},start:()=>{if(!draft||draft.talents.length!==2)return;try{const next=E.create({name:draft.name.trim()||'无名',root:draft.root,path:draft.path,talents:draft.talents,seed:draft.seed});state=next;loadError='';filter='修行';save();close();render();toast('山门外，一段新的仙途开始了。');}catch(error){toast(error.message);}}};
  document.addEventListener('input',event=>{if(event.target.id==='character-name'&&draft)draft.name=event.target.value;});
  document.addEventListener('click',event=>{
    const b=event.target.closest('button');if(!b||b.disabled)return;
    if(b.dataset.command){commands[b.dataset.command]?.();return;}
    if(b.dataset.root){draft.root=b.dataset.root;const scroll=dialog.scrollTop;showNew();dialog.scrollTop=scroll;document.querySelector(`[data-root="${CSS.escape(draft.root)}"]`)?.focus({preventScroll:true});return;}
    if(b.dataset.path){draft.path=b.dataset.path;const scroll=dialog.scrollTop;showNew();dialog.scrollTop=scroll;document.querySelector(`[data-path="${CSS.escape(draft.path)}"]`)?.focus({preventScroll:true});return;}
    if(b.dataset.talent){const id=b.dataset.talent;if(draft.talents.includes(id))draft.talents=draft.talents.filter(t=>t!==id);else if(draft.talents.length<2)draft.talents.push(id);else{toast('已选择两项天赋，先取消一项再更换。');return;}const scroll=dialog.scrollTop;showNew();dialog.scrollTop=scroll;document.querySelector(`[data-talent="${CSS.escape(id)}"]`)?.focus({preventScroll:true});return;}
    if(b.dataset.filter){filter=b.dataset.filter;render();document.querySelector(`[data-filter="${CSS.escape(filter)}"]`)?.focus({preventScroll:true});return;}
    if(b.dataset.action){const id=b.dataset.action;if(mutate(()=>E.addPlan(state,id))){toast(`已安排${find(D.actions,id)?.name} · ${state.plan.length} / 3`);document.querySelector(`[data-action="${CSS.escape(id)}"]:not(:disabled)`)?.focus({preventScroll:true});}return;}
    if(b.dataset.remove!==undefined){mutate(()=>E.removePlan(state,Number(b.dataset.remove)));return;}
    if(b.dataset.choice!==undefined){if(mutate(()=>E.choose(state,Number(b.dataset.choice))))showResult();return;}
    if(b.dataset.jump){jump(b.dataset.jump);return;}
    if(b.dataset.shopTab){shopTab=b.dataset.shopTab;receipt=null;showShop();return;}
    if(b.dataset.buy){const scroll=dialog.scrollTop;if(mutate(()=>{receipt=E.buyItem(state,b.dataset.buy);})){showShop();dialog.scrollTop=scroll;toast(receipt.title);}return;}
    if(b.dataset.use){if(mutate(()=>{receipt=E.useItem(state,b.dataset.use);})){showShop();toast(receipt.title);}return;}
    if(b.dataset.sect){if(mutate(()=>E.joinSect(state,b.dataset.sect))){showSects();toast(`已拜入${find(D.sects,state.sect)?.name}。`);}return;}
  });
  $('#import-file').addEventListener('change',async event=>{const file=event.target.files[0];event.target.value='';if(!file)return;try{if(file.size>1000000)throw Error('存档文件过大，请选择本游戏导出的文件');const raw=JSON.parse(await file.text());if(raw.format!=='XIUXIAN-LIFE')throw Error('这不是仙之巅的存档');const incoming=E.validate(raw.state);modal(`${top('导入仙途 · 确认接续')}${heading(`继续${incoming.name}的仙途？`,`第 ${incoming.year} 年 · ${incoming.age} 岁 · ${E.realmInfo(incoming).name}`)}<div class="notice">确认后会替换当前浏览器中的仙途进度。需要保留当前人生，请先取消并导出。</div><div class="dialog-bottom"><button class="outline-button" data-command="close">取消</button><button class="primary-button" id="confirm-import">确认导入</button></div>`);$('#confirm-import').addEventListener('click',()=>{state=incoming;filter='修行';loadError='';save();close();render();showPhase();toast('存档已导入，仙途可以继续。');},{once:true});}catch(error){toast('导入失败：'+error.message);}});
  render();if(!state)newGame();else showPhase();
  if(document.modelContext?.registerTool){
    const lifecycle=new AbortController(),definitions=[{name:'read_xiuxian_life',description:'读取当前修仙角色、修行计划、行囊和行动条件，不改变进度。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>state?{name:state.name,year:state.year,phase:state.phase,realm:E.realmInfo(state).name,health:state.health,resolve:state.resolve,stones:state.stones,cultivation:state.cultivation,plan:[...state.plan],inventory:{...state.inventory},actions:D.actions.map(a=>({id:a.id,name:a.name,error:E.actionError(state,a.id)}))}:{started:false}},{name:'set_year_plan',description:'安排本年度最多三项修行行动，只安排，不结算。',inputSchema:{type:'object',properties:{actions:{type:'array',items:{type:'string'},maxItems:3}},required:['actions'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!state)throw Error('请先创建修士');if(!input||!Array.isArray(input.actions)||input.actions.length>3||input.actions.some(id=>typeof id!=='string'))throw Error('请提供最多三项行动');E.setPlan(state,input.actions);save();render();return{plan:[...state.plan],executed:false};}}];
    for(const definition of definitions){try{Promise.resolve(document.modelContext.registerTool(definition,{signal:lifecycle.signal})).catch(()=>{});}catch(_){}}
    window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
  }
})();
